[files]
extend-exclude = [
	"**/src/locales/",
	"apps/frontend/",
	"patches/",
	"packages/utils/",
	"packages/ui/",
	"packages/blog/",
]

[default]
extend-ignore-re = [
	# Ignore lines that end with `// typos:ignore`
	"(?Rm)^.*(#|//)\\s*typos:ignore$",
	# Ignore the line after `// typos:ignore`:
	"(#|//)\\s*typos:ignore\\n.*",
	# Ignore blocks between `// typos:off` and `// typos:on`
	"(?s)(#|//)\\s*typos:off.*?\\n\\s*(#|//)\\s*typos:on",
]

[default.extend-words]
# Terms Of Use in `tou-link`
tou = "tou"
# Google Ad Manager
gam = "gam"
# short for "constants"
consts = "consts"
# short for "Copy"
Cpy = "Cpy"

[default.extend-identifiers]
# Constant from the `zip` crate
ZIP64_BYTES_THR = "ZIP64_BYTES_THR"
