version = 1

[schema]

[[schema.tables]]
id = 0
name = "minecraft_versions"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "source_blob_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_minecraft_versions_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 1
name = "download_blobs"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "url"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_download_blobs_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_download_blobs_by_download_run_id_and_url"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 1, index = 2 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 1, index = 2 }
name = "index_download_blobs_by_sha256"
on = 1
columns = [{ column = { table = 1, index = 3 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "download_runs"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "started_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "completed_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "errors"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_download_runs_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 3
name = "json_blobs"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "json"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_json_blobs_by_sha256"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true
