version = 1

[schema]

[[schema.tables]]
id = 0
name = "mojang_catalogs"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_mojang_catalogs_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_mojang_catalogs_by_download_run_id"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "download_runs"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "started_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "completed_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "errors"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_download_runs_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "forge_catalogs"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_forge_catalogs_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_forge_catalogs_by_download_run_id"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 3
name = "forge_installers"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_forge_installers_by_name"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 4
name = "blob_downloads"
primary_key = { columns = [{ table = 4, index = 0 }, { table = 4, index = 1 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "url"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_blob_downloads_by_download_run_id_and_url"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }, { column = { table = 4, index = 1 }, op = "Eq", scope = "Local" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_blob_downloads_by_sha256"
on = 4
columns = [{ column = { table = 4, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 5
name = "blob_hashes"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "sha1"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_blob_hashes_by_sha256"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 5, index = 1 }
name = "index_blob_hashes_by_sha1"
on = 5
columns = [{ column = { table = 5, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 6
name = "fabric_catalogs"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "download_run_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 6, index = 2 }
name = "sha256"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_fabric_catalogs_by_id"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 6, index = 1 }
name = "index_fabric_catalogs_by_download_run_id"
on = 6
columns = [{ column = { table = 6, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
