use std::{
    ffi::OsString,
    path::{Path, PathBuf},
};

use eyre::{Result, ensure};

use crate::{SandboxCommand, SandboxOutput};

#[derive(Debug)]
pub struct MinecraftCommand {
    /// Path to the Java Runtime Environment on the host.
    ///
    /// This will be mounted read-only as `/app/jre` in the sandbox.
    pub jre_path: PathBuf,
    /// Optional Java agent JAR on the host.
    ///
    /// This will be mounted read-only as `/app/agent.jar`.
    pub java_agent: Option<PathBuf>,
    /// Complete Java classpath on the host, in classpath order.
    ///
    /// Each entry is mounted individually and read-only under `/app/classpath`.
    pub classpath: Vec<PathBuf>,
    /// Path to the extracted native libraries on the host.
    ///
    /// This will be mounted read-only as `/app/natives`.
    pub natives_path: PathBuf,
    /// Path to the Minecraft assets directory on the host.
    ///
    /// This will be mounted read-only as `/app/assets`.
    pub assets_path: PathBuf,
    /// Optional version-specific logging configuration.
    pub logging_config: Option<MinecraftLoggingConfig>,
    /// Path to the Minecraft instance directory on the host.
    ///
    /// This is the only persistent read-write mount and is exposed as
    /// `/app/minecraft`.
    pub instance_path: PathBuf,
    /// JVM arguments which do not contain sandbox-managed paths.
    ///
    /// Classpath, Java agent, native-library, and logging arguments are generated
    /// by [`create_minecraft_command`].
    pub jvm_args: Vec<String>,
    /// Java main class to invoke.
    pub main_class: String,
    /// Arguments passed to [`MinecraftCommand::main_class`]. Path arguments must
    /// use paths visible inside the sandbox, such as [`SANDBOX_INSTANCE_PATH`]
    /// and [`SANDBOX_ASSETS_PATH`].
    pub main_class_args: Vec<String>,
    /// Additional environment variables set for the sandboxed process.
    pub extra_environment: Vec<(OsString, OsString)>,
    /// How the Minecraft process exposes stdout and stderr.
    pub output: SandboxOutput,
}

#[derive(Debug)]
pub struct MinecraftLoggingConfig {
    /// Path to the logging configuration file on the host.
    pub path: PathBuf,
    /// JVM argument containing a `${path}` placeholder for the configuration
    /// file's path inside the sandbox.
    pub argument: String,
}

const JRE_PATH: &str = "/app/jre";
const JAVA_PATH: &str = "/app/jre/bin/java";
const JAVA_AGENT_PATH: &str = "/app/agent.jar";
const CLASSPATH_PATH: &str = "/app/classpath";
const NATIVES_PATH: &str = "/app/natives";
pub const SANDBOX_ASSETS_PATH: &str = "/app/assets";
pub const SANDBOX_INSTANCE_PATH: &str = "/app/minecraft";

const LOGGING_CONFIG_PATH: &str = "/app/logging.xml";

const CLASSPATH_JVM_ARGUMENT: &str = "-cp";
const JAVA_LIBRARY_PATH_JVM_ARGUMENT: &str = "-Djava.library.path";
const JNA_TMPDIR_JVM_ARGUMENT: &str = "-Djna.tmpdir";
const LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT: &str =
    "-Dorg.lwjgl.system.SharedLibraryExtractPath";
const NETTY_NATIVE_WORKDIR_JVM_ARGUMENT: &str = "-Dio.netty.native.workdir";
const LOGGING_CONFIG_JVM_ARGUMENT: &str = "-Dlog4j.configurationFile";
const JAVA_AGENT_JVM_ARGUMENT: &str = "-javaagent";

/// JVM options generated by [`create_minecraft_command`].
///
/// Entries are option names without their `=` or `:` separated values.
pub const MINECRAFT_JVM_ARGUMENTS: &[&str] = &[
    CLASSPATH_JVM_ARGUMENT,
    JAVA_LIBRARY_PATH_JVM_ARGUMENT,
    JNA_TMPDIR_JVM_ARGUMENT,
    LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT,
    NETTY_NATIVE_WORKDIR_JVM_ARGUMENT,
    LOGGING_CONFIG_JVM_ARGUMENT,
    JAVA_AGENT_JVM_ARGUMENT,
];

const MINECRAFT_PASSTHROUGH_ENVIRONMENT: &[&str] = &[
    "DISPLAY",
    "WAYLAND_DISPLAY",
    "XDG_RUNTIME_DIR",
    "XAUTHORITY",
    "XDG_SESSION_TYPE",
    "PIPEWIRE_REMOTE",
    "PULSE_SERVER",
    "LANG",
    "LANGUAGE",
    "LC_ALL",
    "LC_ADDRESS",
    "LC_COLLATE",
    "LC_CTYPE",
    "LC_IDENTIFICATION",
    "LC_MEASUREMENT",
    "LC_MESSAGES",
    "LC_MONETARY",
    "LC_NAME",
    "LC_NUMERIC",
    "LC_PAPER",
    "LC_TELEPHONE",
    "LC_TIME",
    "TZ",
    "DRI_PRIME",
    "MESA_LOADER_DRIVER_OVERRIDE",
    "MESA_VK_DEVICE_SELECT",
    "MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE",
    "LIBGL_ALWAYS_SOFTWARE",
    "__GLX_VENDOR_LIBRARY_NAME",
    "__NV_PRIME_RENDER_OFFLOAD",
    "__NV_PRIME_RENDER_OFFLOAD_PROVIDER",
    "__VK_LAYER_NV_optimus",
    "VK_DRIVER_FILES",
    "VK_ICD_FILENAMES",
    "VK_LAYER_PATH",
    "VK_LOADER_DRIVERS_SELECT",
    "VK_LOADER_DRIVERS_DISABLE",
    "FREETYPE_PROPERTIES",
    "ALSOFT_DRIVERS",
    "SDL_AUDIODRIVER",
    "GLFW_IM_MODULE",
    "XMODIFIERS",
    "SDL_IM_MODULE",
];

pub fn create_minecraft_command(
    minecraft: MinecraftCommand,
) -> Result<SandboxCommand> {
    let mut read_only_paths = vec![
        (minecraft.jre_path, PathBuf::from(JRE_PATH)),
        (minecraft.natives_path, PathBuf::from(NATIVES_PATH)),
        (minecraft.assets_path, PathBuf::from(SANDBOX_ASSETS_PATH)),
    ];

    let mut classpath = Vec::with_capacity(minecraft.classpath.len());
    for (index, host_path) in minecraft.classpath.into_iter().enumerate() {
        let sandbox_path = sandbox_classpath_path(index, &host_path)?;
        read_only_paths.push((host_path, sandbox_path.clone()));
        classpath.push(sandbox_path);
    }

    let mut args = minecraft.jvm_args;
    args.extend([
        format!("{JAVA_LIBRARY_PATH_JVM_ARGUMENT}={NATIVES_PATH}"),
        format!("{JNA_TMPDIR_JVM_ARGUMENT}=/tmp"),
        format!("{LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT}=/tmp"),
        format!("{NETTY_NATIVE_WORKDIR_JVM_ARGUMENT}=/tmp"),
    ]);

    if let Some(java_agent) = minecraft.java_agent {
        read_only_paths.push((java_agent, PathBuf::from(JAVA_AGENT_PATH)));
        args.push(format!("{JAVA_AGENT_JVM_ARGUMENT}:{JAVA_AGENT_PATH}"));
    }

    if let Some(logging_config) = minecraft.logging_config {
        ensure!(
            logging_config.argument.contains("${path}"),
            "logging configuration argument must contain a `${{path}}` placeholder"
        );
        read_only_paths
            .push((logging_config.path, PathBuf::from(LOGGING_CONFIG_PATH)));
        args.push(
            logging_config
                .argument
                .replace("${path}", LOGGING_CONFIG_PATH),
        );
    }

    args.push(CLASSPATH_JVM_ARGUMENT.to_string());
    args.push(
        classpath
            .iter()
            .map(|path| path.to_string_lossy())
            .collect::<Vec<_>>()
            .join(":"),
    );
    args.push(minecraft.main_class);
    args.extend(minecraft.main_class_args);

    let mut extra_environment = vec![
        (OsString::from("JAVA_HOME"), OsString::from(JRE_PATH)),
        (
            OsString::from("PATH"),
            OsString::from(format!("{JRE_PATH}/bin")),
        ),
    ];
    extra_environment.extend(minecraft.extra_environment);

    Ok(SandboxCommand {
        executable: JAVA_PATH.to_string(),
        args,
        read_only_paths,
        read_write_paths: vec![(
            minecraft.instance_path,
            PathBuf::from(SANDBOX_INSTANCE_PATH),
        )],
        working_directory: Some(PathBuf::from(SANDBOX_INSTANCE_PATH)),
        passthrough_environment: MINECRAFT_PASSTHROUGH_ENVIRONMENT
            .iter()
            .map(OsString::from)
            .collect(),
        extra_environment,
        output: minecraft.output,
        system_runtime: true,
        network: true,
        graphics: true,
        audio: true,
    })
}

fn sandbox_classpath_path(index: usize, host_path: &Path) -> Result<PathBuf> {
    let file_name = host_path.file_name().ok_or_else(|| {
        eyre::eyre!("classpath entry has no filename: {host_path:?}")
    })?;
    let mut sandbox_file_name = OsString::from(format!("{index}-"));
    sandbox_file_name.push(file_name);

    Ok(PathBuf::from(CLASSPATH_PATH).join(sandbox_file_name))
}
