use std::{
    ffi::OsString,
    path::{Path, PathBuf},
};

use eyre::{Result, ensure};

use crate::{SandboxCommand, SandboxOutput};

#[derive(Debug)]
pub struct MinecraftCommand {
    /// Path to the Java Runtime Environment on the host.
    pub jre_path: PathBuf,
    /// Optional Java agent JAR on the host.
    pub java_agent: Option<PathBuf>,
    /// Complete Java classpath on the host, in classpath order.
    pub classpath: Vec<PathBuf>,
    /// Path to the extracted native libraries on the host.
    pub natives_path: PathBuf,
    /// Path to the Minecraft assets directory on the host.
    pub assets_path: PathBuf,
    /// Optional version-specific logging configuration.
    pub logging_config: Option<MinecraftLoggingConfig>,
    /// Path to the Minecraft instance directory on the host.
    pub instance_path: PathBuf,
    /// Directory for persistent home, data, configuration, cache, and state,
    /// shared across all game instances.
    pub persistent_dir: PathBuf,
    /// JVM arguments which do not contain sandbox-managed paths.
    ///
    /// Classpath, Java agent, native-library, and logging arguments are generated
    /// by [`create_minecraft_command`].
    pub jvm_args: Vec<OsString>,
    /// Java main class to invoke.
    pub main_class: String,
    /// Arguments passed to [`MinecraftCommand::main_class`].
    pub main_class_args: Vec<String>,
    /// Additional environment variables set for the sandboxed process.
    pub extra_environment: Vec<(OsString, OsString)>,
    /// How the Minecraft process exposes stdout and stderr.
    pub output: SandboxOutput,
}

#[derive(Debug)]
pub struct MinecraftLoggingConfig {
    /// Path to the logging configuration file on the host.
    pub path: PathBuf,
    /// JVM argument containing a `${path}` placeholder for the configuration
    /// file's path inside the sandbox.
    pub argument: String,
}

const CLASSPATH_JVM_ARGUMENT: &str = "-cp";
const JAVA_LIBRARY_PATH_JVM_ARGUMENT: &str = "-Djava.library.path";
const JNA_TMPDIR_JVM_ARGUMENT: &str = "-Djna.tmpdir";
const LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT: &str =
    "-Dorg.lwjgl.system.SharedLibraryExtractPath";
const NETTY_NATIVE_WORKDIR_JVM_ARGUMENT: &str = "-Dio.netty.native.workdir";
const USER_HOME_JVM_ARGUMENT: &str = "-Duser.home";
const LOGGING_CONFIG_JVM_ARGUMENT: &str = "-Dlog4j.configurationFile";
const JAVA_AGENT_JVM_ARGUMENT: &str = "-javaagent";

/// JVM options generated by [`create_minecraft_command`].
///
/// Entries are option names without their `=` or `:` separated values.
pub const MINECRAFT_JVM_ARGUMENTS: &[&str] = &[
    CLASSPATH_JVM_ARGUMENT,
    JAVA_LIBRARY_PATH_JVM_ARGUMENT,
    JNA_TMPDIR_JVM_ARGUMENT,
    LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT,
    NETTY_NATIVE_WORKDIR_JVM_ARGUMENT,
    USER_HOME_JVM_ARGUMENT,
    LOGGING_CONFIG_JVM_ARGUMENT,
    JAVA_AGENT_JVM_ARGUMENT,
];

const MINECRAFT_PASSTHROUGH_ENVIRONMENT: &[&str] = &[
    "DISPLAY",
    "WAYLAND_DISPLAY",
    "XDG_RUNTIME_DIR",
    "XAUTHORITY",
    "XDG_SESSION_TYPE",
    "PIPEWIRE_REMOTE",
    "PULSE_SERVER",
    "LANG",
    "LANGUAGE",
    "LC_ALL",
    "LC_ADDRESS",
    "LC_COLLATE",
    "LC_CTYPE",
    "LC_IDENTIFICATION",
    "LC_MEASUREMENT",
    "LC_MESSAGES",
    "LC_MONETARY",
    "LC_NAME",
    "LC_NUMERIC",
    "LC_PAPER",
    "LC_TELEPHONE",
    "LC_TIME",
    "TZ",
    "DRI_PRIME",
    "MESA_LOADER_DRIVER_OVERRIDE",
    "MESA_VK_DEVICE_SELECT",
    "MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE",
    "LIBGL_ALWAYS_SOFTWARE",
    "__GLX_VENDOR_LIBRARY_NAME",
    "__NV_PRIME_RENDER_OFFLOAD",
    "__NV_PRIME_RENDER_OFFLOAD_PROVIDER",
    "__VK_LAYER_NV_optimus",
    "VK_DRIVER_FILES",
    "VK_ICD_FILENAMES",
    "VK_LAYER_PATH",
    "VK_LOADER_DRIVERS_SELECT",
    "VK_LOADER_DRIVERS_DISABLE",
    "FREETYPE_PROPERTIES",
    "ALSOFT_DRIVERS",
    "SDL_AUDIODRIVER",
    "GLFW_IM_MODULE",
    "XMODIFIERS",
    "SDL_IM_MODULE",
];

pub fn create_minecraft_command(
    minecraft: MinecraftCommand,
) -> Result<SandboxCommand> {
    let java_path = minecraft.jre_path.join("bin/java");
    let persistent_home = minecraft.persistent_dir.join("home");
    let persistent_data = minecraft.persistent_dir.join("data");
    let persistent_config = minecraft.persistent_dir.join("config");
    let persistent_cache = minecraft.persistent_dir.join("cache");
    let persistent_state = minecraft.persistent_dir.join("state");
    let mods_path = minecraft.instance_path.join("mods");
    let classpath = minecraft.classpath;
    let mut read_only_paths = vec![
        minecraft.jre_path.as_os_str().to_os_string(),
        minecraft.natives_path.as_os_str().to_os_string(),
        minecraft.assets_path.as_os_str().to_os_string(),
        mods_path.into_os_string(),
    ];
    read_only_paths
        .extend(classpath.iter().map(|path| path.as_os_str().to_os_string()));

    let mut args = minecraft.jvm_args;
    args.extend([
        jvm_path_argument(
            JAVA_LIBRARY_PATH_JVM_ARGUMENT,
            "=",
            &minecraft.natives_path,
        ),
        OsString::from(format!("{JNA_TMPDIR_JVM_ARGUMENT}=/tmp")),
        OsString::from(format!(
            "{LWJGL_LIBRARY_EXTRACT_PATH_JVM_ARGUMENT}=/tmp"
        )),
        OsString::from(format!("{NETTY_NATIVE_WORKDIR_JVM_ARGUMENT}=/tmp")),
        jvm_path_argument(USER_HOME_JVM_ARGUMENT, "=", &persistent_home),
    ]);

    if let Some(java_agent) = minecraft.java_agent {
        read_only_paths.push(java_agent.as_os_str().to_os_string());
        args.push(jvm_path_argument(JAVA_AGENT_JVM_ARGUMENT, ":", &java_agent));
    }

    if let Some(logging_config) = minecraft.logging_config {
        ensure!(
            logging_config.argument.contains("${path}"),
            "logging configuration argument must contain a `${{path}}` placeholder"
        );
        read_only_paths.push(logging_config.path.as_os_str().to_os_string());
        args.push(replace_path_placeholder(
            &logging_config.argument,
            &logging_config.path,
        ));
    }

    args.push(OsString::from(CLASSPATH_JVM_ARGUMENT));
    args.push(std::env::join_paths(&classpath)?);
    args.push(OsString::from(minecraft.main_class));
    args.extend(minecraft.main_class_args.into_iter().map(OsString::from));

    let mut extra_environment = minecraft.extra_environment;
    extra_environment.extend([
        (
            OsString::from("JAVA_HOME"),
            minecraft.jre_path.as_os_str().to_os_string(),
        ),
        (
            OsString::from("PATH"),
            minecraft.jre_path.join("bin").into_os_string(),
        ),
        (OsString::from("HOME"), persistent_home.into_os_string()),
        (
            OsString::from("XDG_DATA_HOME"),
            persistent_data.into_os_string(),
        ),
        (
            OsString::from("XDG_CONFIG_HOME"),
            persistent_config.into_os_string(),
        ),
        (
            OsString::from("XDG_CACHE_HOME"),
            persistent_cache.into_os_string(),
        ),
        (
            OsString::from("XDG_STATE_HOME"),
            persistent_state.into_os_string(),
        ),
    ]);

    read_only_paths.sort_unstable();
    read_only_paths.dedup();

    let mut read_write_paths = vec![
        minecraft.instance_path.as_os_str().to_os_string(),
        minecraft.persistent_dir.as_os_str().to_os_string(),
    ];
    read_write_paths.sort_unstable();
    read_write_paths.dedup();

    Ok(SandboxCommand {
        executable: java_path.into_os_string(),
        args,
        read_only_paths,
        read_write_paths,
        working_directory: Some(minecraft.instance_path),
        passthrough_environment: MINECRAFT_PASSTHROUGH_ENVIRONMENT
            .iter()
            .map(OsString::from)
            .collect(),
        extra_environment,
        output: minecraft.output,
        network: true,
        is_jvm: true,
        die_with_parent: true,
    })
}

fn jvm_path_argument(argument: &str, separator: &str, path: &Path) -> OsString {
    let mut result = OsString::from(argument);
    result.push(separator);
    result.push(path);
    result
}

fn replace_path_placeholder(argument: &str, path: &Path) -> OsString {
    let (prefix, suffix) = argument
        .split_once("${path}")
        .expect("logging argument placeholder was validated");
    let mut result = OsString::from(prefix);
    result.push(path);
    result.push(suffix);
    result
}
