export const PROJECT_LINK_DOMAIN_LIST = {
	common: {
		source: [
			'github.com',
			'gitlab.com',
			'bitbucket.org',
			'codeberg.org',
			'git.sr.ht',
			'tangled.org',
			'git.gay',
		],
		issues: [
			'github.com',
			'gitlab.com',
			'bitbucket.org',
			'codeberg.org',
			'docs.google.com',
			'tangled.org',
			'git.gay',
		],
		discord: ['discord.gg', 'discord.com', 'dsc.gg'],
	},
	inappropriateLicense: [
		'youtube.com',
		'youtu.be',
		'modrinth.com',
		'curseforge.com',
		'twitter.com',
		'x.com',
		'discord.gg',
		'discord.com',
		'instagram.com',
		'facebook.com',
		'tiktok.com',
		'reddit.com',
		'twitch.tv',
		'patreon.com',
		'ko-fi.com',
		'paypal.com',
		'buymeacoffee.com',
		'google.com',
		'example.com',
		't.me',
	],
} as const
