//! Protocol 2 seals the new session token to an ephemeral P-256 key generated by the app.
//!
//! Wire format, base64url without padding:
//! `version || spki_len || spki || iv || ciphertext`
//! - `version`: 1 byte, `0x02`
//! - `spki_len`: 2 bytes, big-endian length of the ephemeral P-256 SubjectPublicKeyInfo
//! - `spki`: ephemeral public key, DER SubjectPublicKeyInfo
//! - `iv`: 12-byte AES-GCM nonce
//! - `ciphertext`: AES-256-GCM ciphertext with the 16-byte tag appended
//!
//! The AES key is HKDF-SHA256 over the ECDH shared secret (the P-256 x coordinate):
//! salt is 32 zero bytes, info is `modrinth-app-auth-v2`, and the output is 32 bytes.
//! Plaintext is UTF-8 `{nonce}.{sessionToken}`.

use aes_gcm::aead::Aead;
use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use hkdf::Hkdf;
use p256::PublicKey;
use p256::SecretKey;
use p256::ecdh::diffie_hellman;
use p256::pkcs8::{DecodePublicKey, EncodePublicKey};
use rand::RngCore;
use rand::rngs::OsRng;
use sha2::Sha256;

const SEAL_VERSION: u8 = 2;
const PROTOCOL_INFO: &[u8] = b"modrinth-app-auth-v2";
const MAX_SEALED_LEN: usize = 4096;
const MAX_EPHEMERAL_SPKI_LEN: usize = 256;

pub struct AuthSeal {
    secret: SecretKey,
    nonce: String,
}

impl AuthSeal {
    pub fn generate() -> Self {
        let secret = SecretKey::random(&mut OsRng);
        let mut nonce_bytes = [0u8; 16];
        OsRng.fill_bytes(&mut nonce_bytes);

        Self {
            secret,
            nonce: URL_SAFE_NO_PAD.encode(nonce_bytes),
        }
    }

    pub fn nonce(&self) -> &str {
        &self.nonce
    }

    pub fn public_key(&self) -> Result<String, theseus::Error> {
        let der =
            self.secret
                .public_key()
                .to_public_key_der()
                .map_err(|error| {
                    theseus::ErrorKind::OtherError(format!(
                        "Failed to encode auth public key: {error}"
                    ))
                })?;

        Ok(URL_SAFE_NO_PAD.encode(der.as_bytes()))
    }

    pub fn open(&self, sealed: &str) -> Result<String, theseus::Error> {
        open_session(&self.secret, sealed, &self.nonce)
    }
}

fn open_session(
    secret: &SecretKey,
    sealed: &str,
    expected_nonce: &str,
) -> Result<String, theseus::Error> {
    if sealed.len() > MAX_SEALED_LEN {
        return Err(invalid_sealed_session());
    }

    let bytes = URL_SAFE_NO_PAD
        .decode(sealed)
        .map_err(|_| invalid_sealed_session())?;
    if bytes.first() != Some(&SEAL_VERSION) || bytes.len() < 3 {
        return Err(invalid_sealed_session());
    }

    let spki_len = u16::from_be_bytes([bytes[1], bytes[2]]) as usize;
    let header_len = 3 + spki_len + 12;
    if spki_len == 0
        || spki_len > MAX_EPHEMERAL_SPKI_LEN
        || bytes.len() < header_len + 16
    {
        return Err(invalid_sealed_session());
    }

    let spki = &bytes[3..3 + spki_len];
    let iv = &bytes[3 + spki_len..header_len];
    let ciphertext = &bytes[header_len..];
    let ephemeral_public = PublicKey::from_public_key_der(spki)
        .map_err(|_| invalid_sealed_session())?;
    let cipher = derive_cipher(secret, &ephemeral_public)?;
    let mut iv_bytes = [0u8; 12];
    iv_bytes.copy_from_slice(iv);
    let plaintext = cipher
        .decrypt(&Nonce::from(iv_bytes), ciphertext)
        .map_err(|_| invalid_sealed_session())?;
    let plaintext = std::str::from_utf8(&plaintext)
        .map_err(|_| invalid_sealed_session())?;
    let (nonce, token) = plaintext
        .split_once('.')
        .ok_or_else(invalid_sealed_session)?;

    if nonce != expected_nonce || !is_session_token(token) {
        return Err(invalid_sealed_session());
    }

    Ok(token.to_string())
}

fn derive_cipher(
    secret: &SecretKey,
    public: &PublicKey,
) -> Result<Aes256Gcm, theseus::Error> {
    let shared = diffie_hellman(secret.to_nonzero_scalar(), public.as_affine());
    let mut aes_key = [0u8; 32];
    Hkdf::<Sha256>::new(None, shared.raw_secret_bytes())
        .expand(PROTOCOL_INFO, &mut aes_key)
        .map_err(|_| invalid_sealed_session())?;

    Aes256Gcm::new_from_slice(&aes_key).map_err(|_| invalid_sealed_session())
}

fn is_session_token(token: &str) -> bool {
    let Some(rest) = token.strip_prefix("mra_") else {
        return false;
    };

    (32..=128).contains(&rest.len())
        && rest
            .chars()
            .all(|character| character.is_ascii_alphanumeric())
}

fn invalid_sealed_session() -> theseus::Error {
    theseus::ErrorKind::OtherError("Invalid sealed app sign-in session".into())
        .into()
}
