name: 🎮 Modrinth App bug
description: Report an issue in the Modrinth Launcher.
labels: [bug, app]
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
          required: true
        - label: I have tried resolving the issue using the [support portal](https://support.modrinth.com)
          required: true
        - label: I have ensured my Modrinth App installation is up to date
          required: true
  - type: input
    id: version
    attributes:
      label: What version of the Modrinth App are you using?
      description: Find this in ⚙️ Settings (bottom right) -> About -> App version.
    validations:
      required: true
  - type: dropdown
    id: oses
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Include screenshots if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false