name: 👥 Bug with Modrinth Servers
description: For issues with a Modrinth Servers product.
labels: [servers]
type: 'bug'
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
          required: true
        - label: I have tried resolving the issue using the [support portal](https://support.modrinth.com)
          required: true
  - type: dropdown
    id: issue-location
    attributes:
      label: Is this an issue in the control panel or with the Minecraft server itself?
      options:
        - Control panel (on Modrinth.com)
        - Minecraft server
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? (if a panel issue)
      multiple: true
      options:
        - N/A
        - Chrome (including Arc, Brave, Opera, Vivaldi)
        - Microsoft Edge
        - Firefox
        - Safari
        - Other (please specify)
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Include screenshots if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
