import type { ComboboxOption } from '@modrinth/ui'

/** Java Edition language names and regions from https://github.com/misode/mcmeta/blob/assets/pack.mcmeta. */
const languageNames: Record<string, string> = {
	en_us: 'English (US)',
	af_za: 'Afrikaans (Suid-Afrika)',
	esan: 'Andalûh (Andaluçía)',
	enp: 'Anglish (Oned Riches)',
	ast_es: 'Asturianu (Asturies)',
	az_az: 'Azərbaycanca (Azərbaycan)',
	id_id: 'Bahasa Indonesia (Indonesia)',
	ms_my: 'Bahasa Melayu (Malaysia)',
	tzo_mx: 'Bats\'i k\'op (Jobel)',
	qid: 'Bhs. Indonesia edjaän lama (Indonesia tempo doeloe)',
	be_latn: 'Biełaruskaja (Biełaruś)',
	bar: 'Boarisch (Bayern)',
	bs_ba: 'Bosanski (Bosna i Hercegovina)',
	brb: 'Braobans (Braobant)',
	br_fr: 'Brezhoneg (Breizh)',
	ca_es: 'Català (Catalunya)',
	val_es: 'Català (Valencià) (País Valencià)',
	cy_gb: 'Cymraeg (Cymru)',
	qcb_es: 'Cántabru/Montañés (Cantabria)',
	da_dk: 'Dansk (Danmark)',
	se_no: 'Davvisámegiella (Sápmi)',
	de_at: 'Deitsch (Österreich)',
	de_de: 'Deutsch (Deutschland)',
	et_ee: 'Eesti keel (Eesti)',
	en_au: 'English (Australia)',
	en_ca: 'English (Canada)',
	en_nz: 'English (New Zealand)',
	en_gb: 'English (United Kingdom)',
	es_ar: 'Español (Argentina)',
	es_cl: 'Español (Chile)',
	es_ec: 'Español (Ecuador)',
	es_es: 'Español (España)',
	es_mx: 'Español (México)',
	es_uy: 'Español (Uruguay)',
	es_ve: 'Español (Venezuela)',
	eo_uy: 'Esperanto (Esperantujo)',
	eu_es: 'Euskara (Euskal Herria)',
	fil_ph: 'Filipino (Pilipinas)',
	fr_ca: 'Français (Canada)',
	fr_fr: 'Français (France)',
	fr_ch: 'Français (Suisse)',
	fy_nl: 'Frysk (Fryslân)',
	fra_de: 'Fränggisch (Franggn)',
	fur_it: 'Furlan (Friûl)',
	fo_fo: 'Føroyskt (Føroyar)',
	ga_ie: 'Gaeilge (Éire)',
	gl_es: 'Galego (Galicia / Galiza)',
	go_fr: 'Galo (Bertègn)',
	gd_gb: 'Gàidhlig (Alba)',
	hr_hr: 'Hrvatski (Hrvatska)',
	hn_no: 'Høgnorsk (Norig)',
	io_en: 'Ido (Idia)',
	ig_ng: 'Igbo (Naigeria)',
	it_it: 'Italiano (Italia)',
	kw_gb: 'Kernewek (Kernow)',
	ksh: 'Kölsch/Ripoarisch (Rhingland)',
	lol_us: 'LOLCAT (Kingdom of Cats)',
	la_la: 'Latina (Latium)',
	lv_lv: 'Latviešu (Latvija)',
	lt_lt: 'Lietuvių (Lietuva)',
	li_li: 'Limburgs (Limburg)',
	lmo: 'Lombard (Lombardia)',
	lb_lu: 'Lëtzebuergesch (Lëtzebuerg)',
	hu_hu: 'Magyar (Magyarország)',
	mt_mt: 'Malti (Malta)',
	isv: 'Medžuslovjansky (Slovjanščina)',
	nah: 'Mēxikatlahtōlli (Mēxiko)',
	nl_nl: 'Nederlands (Nederland)',
	pls: 'Ngiiwà (Ndanìꞌngà)',
	no_no: 'Norsk bokmål (Norge)',
	nn_no: 'Norsk nynorsk (Noreg)',
	uz_uz: 'O\'zbekcha (O\'zbekiston)',
	oc_fr: 'Occitan (Occitània)',
	en_pt: 'Pirate Speak (The Seven Seas)',
	nds_de: 'Plattdüütsch (Düütschland)',
	pl_pl: 'Polski (Polska)',
	pt_br: 'Português (Brasil)',
	pt_pt: 'Português (Portugal)',
	qya_aa: 'Quenya (Arda)',
	ro_ro: 'Română (România)',
	de_ch: 'Schwiizerdütsch (Schwiiz)',
	enws: 'Shakespearean English (Kingdom of England)',
	sq_al: 'Shqip (Shqipëri)',
	sk_sk: 'Slovenčina (Slovensko)',
	sl_si: 'Slovenščina (Slovenija)',
	so_so: 'Soomaali (Soomaaliya)',
	sr_cs: 'Srpski (Srbija)',
	fi_fi: 'Suomi (Suomi)',
	sv_se: 'Svenska (Sverige)',
	sxu: 'Säggs’sch (Saggsn)',
	tl_ph: 'Tagalog (Pilipinas)',
	vi_vn: 'Tiếng Việt (Việt Nam)',
	tr_tr: 'Türkçe (Türkiye)',
	vp_vl: 'Viossa (Vilant)',
	nl_be: 'Vlaams (België)',
	vec_it: 'Vèneto (Veneto)',
	vro: 'Võro (Eesti)',
	yo_ng: 'Yorùbá (Nàìjíríà)',
	jbo_en: 'la .lojban. (la jbogu\'e)',
	tlh_aa: 'tlhIngan Hol (tlhIngan wo\')',
	tok: 'toki pona (kulupu pona)',
	is_is: 'Íslenska (Ísland)',
	ovd: 'Övdalska (Swerre)',
	cs_cz: 'Čeština (Česko)',
	szl: 'Ślōnski (Gōrny Ślōnsk)',
	en_ud: 'ɥsᴉꞁᵷuƎ (uʍoᗡ ǝpᴉsd∩)',
	haw_us: 'ʻŌlelo Hawaiʻi (Hawaiʻi)',
	el_gr: 'Ελληνικά (Ελλάδα)',
	ba_ru: 'Башҡортса (Башҡортостан, Рәсәй)',
	be_by: 'Беларуская (Беларусь)',
	bg_bg: 'Български (България)',
	hal_ua: 'Галицка (Галичина, Вкраїна)',
	ky_kg: 'Кыргызча (Кыргызстан)',
	mk_mk: 'Македонски (Северна Македонија)',
	mn_mn: 'Монгол (Монгол Улс)',
	ry_ua: 'Руснацькый (Пудкарпатя, Украина)',
	ru_ru: 'Русский (Россия)',
	rpr: 'Русскій дореформенный (Россійская имперія)',
	sah_sah: 'Сахалыы (Cаха Сирэ)',
	sr_sp: 'Српски (Србија)',
	tt_ru: 'Татарча (Татарстан, Рәсәй)',
	uk_ua: 'Українська (Україна)',
	cv_cu: 'Чӑвашла (Чӑваш Ен, Раҫҫей)',
	kk_kz: 'Қазақша (Қазақстан)',
	hy_am: 'Հայերեն (Հայաստան)',
	yi_de: 'ייִדיש (אשכנזיש יידן)',
	he_il: 'עברית (ישראל)',
	ar_sa: 'العربية (العالم العربي)',
	zlm_arab: 'بهاس ملايو (مليسيا)',
	fa_ir: 'فارسی (ايران)',
	hi_in: 'हिंदी (भारत)',
	ta_in: 'தமிழ் (இந்தியா)',
	kn_in: 'ಕನ್ನಡ (ಭಾರತ)',
	th_th: 'ไทย (ประเทศไทย)',
	lo_la: 'ລາວ (ປະເທດລາວ)',
	ka_ge: 'ქართული (საქართველო)',
	lzh: '文言 (華夏)',
	ja_jp: '日本語 (日本)',
	zh_cn: '简体中文 (中国大陆)',
	zh_tw: '繁體中文 (台灣)',
	zh_hk: '繁體中文 (香港特別行政區)',
	ko_kr: '한국어 (대한민국)',
	got_de: '𐌲𐌿𐍄𐍂𐌰𐌶𐌳𐌰 (𐌲𐌿𐍄𐌸𐌹𐌿𐌳𐌰)',
}

export const minecraftLanguageOptions: ComboboxOption<string>[] = Object.entries(languageNames)
	.map(([value, label]) => ({ value, label, searchTerms: [value] }))
	.sort((a, b) => a.label.localeCompare(b.label))
