FROM mcr.microsoft.com/devcontainers/base:1-bookworm

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        postgresql-client \
        libssl-dev \
        pkg-config \
        liblzma-dev
