ALTER TABLE categories ADD COLUMN ordering BIGINT NOT NULL DEFAULT 0;
ALTER TABLE mods_gallery ADD COLUMN ordering BIGINT NOT NULL DEFAULT 0;
ALTER TABLE team_members ADD COLUMN ordering BIGINT NOT NULL DEFAULT 0;