INSERT INTO link_platforms (name, donation) VALUES ('store', false);

INSERT INTO categories (header, category, project_type)
VALUES
	('minecraft_server_gameplay', 'skyblock', 2),
	('minecraft_server_gameplay', 'oneblock', 2),
	('minecraft_server_gameplay', 'gens', 2),
	('minecraft_server_gameplay', 'prison', 2),
	('minecraft_server_gameplay', 'factions', 2),
	('minecraft_server_gameplay', 'lifesteal', 2),
	('minecraft_server_gameplay', 'anarchy', 2),
	('minecraft_server_gameplay', 'towns', 2),
	('minecraft_server_gameplay', 'vanilla-like', 2),
	('minecraft_server_gameplay', 'rpg', 2),
	('minecraft_server_gameplay', 'minigames', 2),
	('minecraft_server_gameplay', 'racing', 2),
	('minecraft_server_gameplay', 'battle-royale', 2),
	('minecraft_server_gameplay', 'parkour', 2),
	('minecraft_server_gameplay', 'bedwars', 2),
	('minecraft_server_gameplay', 'kitpvp', 2),
	('minecraft_server_gameplay', 'microgames', 2),

	('minecraft_server_features', 'pokemon', 2),
	('minecraft_server_features', 'teams', 2),
	('minecraft_server_features', 'pvp', 2),
	('minecraft_server_features', 'pve', 2),
	('minecraft_server_features', 'op', 2),
	('minecraft_server_features', 'economy', 2),
	('minecraft_server_features', 'plots', 2),
	('minecraft_server_features', 'questing', 2),
	('minecraft_server_features', 'personal-worlds', 2),
	('minecraft_server_features', 'media', 2),
	('minecraft_server_features', 'bosses', 2),
	('minecraft_server_features', 'classes', 2),
	('minecraft_server_features', 'custom-content', 2),
	('minecraft_server_features', 'dungeons', 2),

	('minecraft_server_meta', 'crossplay', 2),
	('minecraft_server_meta', 'offline-mode', 2),
	('minecraft_server_meta', 'whitelisted', 2),
	('minecraft_server_meta', 'keep-inventory', 2),
	('minecraft_server_meta', 'network', 2),
	('minecraft_server_meta', 'world-resets', 2),
	('minecraft_server_meta', 'creative-mode', 2),
	('minecraft_server_meta', 'hardcore-mode', 2),
	('minecraft_server_meta', 'survival-mode', 2),
	('minecraft_server_meta', 'adventure-mode', 2),

	('minecraft_server_community', 'adventure-mode', 2),
	('minecraft_server_community', 'smp', 2),
	('minecraft_server_community', 'mmo', 2),
	('minecraft_server_community', 'roleplay', 2),
	('minecraft_server_community', 'social', 2),
	('minecraft_server_community', 'creator-community', 2),
	('minecraft_server_community', 'recording-smp', 2),
	('minecraft_server_community', 'competitive', 2),
	('minecraft_server_community', 'technical', 2);
