INSERT INTO link_platforms (name, donation) VALUES ('store', false);

INSERT INTO project_types (id, name)
VALUES (7, 'minecraft_java_server');

INSERT INTO categories (header, category, project_type)
VALUES
	('minecraft_server_gameplay', 'skyblock', 7),
	('minecraft_server_gameplay', 'oneblock', 7),
	('minecraft_server_gameplay', 'gens', 7),
	('minecraft_server_gameplay', 'prison', 7),
	('minecraft_server_gameplay', 'factions', 7),
	('minecraft_server_gameplay', 'lifesteal', 7),
	('minecraft_server_gameplay', 'anarchy', 7),
	('minecraft_server_gameplay', 'towns', 7),
	('minecraft_server_gameplay', 'vanilla-like', 7),
	('minecraft_server_gameplay', 'rpg', 7),
	('minecraft_server_gameplay', 'minigames', 7),
	('minecraft_server_gameplay', 'racing', 7),
	('minecraft_server_gameplay', 'battle-royale', 7),
	('minecraft_server_gameplay', 'parkour', 7),
	('minecraft_server_gameplay', 'bedwars', 7),
	('minecraft_server_gameplay', 'kitpvp', 7),
	('minecraft_server_gameplay', 'microgames', 7),

	('minecraft_server_features', 'pokemon', 7),
	('minecraft_server_features', 'teams', 7),
	('minecraft_server_features', 'pvp', 7),
	('minecraft_server_features', 'pve', 7),
	('minecraft_server_features', 'op', 7),
	('minecraft_server_features', 'economy', 7),
	('minecraft_server_features', 'plots', 7),
	('minecraft_server_features', 'questing', 7),
	('minecraft_server_features', 'personal-worlds', 7),
	('minecraft_server_features', 'media', 7),
	('minecraft_server_features', 'bosses', 7),
	('minecraft_server_features', 'classes', 7),
	('minecraft_server_features', 'custom-content', 7),
	('minecraft_server_features', 'dungeons', 7),

	('minecraft_server_meta', 'crossplay', 7),
	('minecraft_server_meta', 'offline-mode', 7),
	('minecraft_server_meta', 'whitelisted', 7),
	('minecraft_server_meta', 'keep-inventory', 7),
	('minecraft_server_meta', 'network', 7),
	('minecraft_server_meta', 'world-resets', 7),
	('minecraft_server_meta', 'creative-mode', 7),
	('minecraft_server_meta', 'hardcore-mode', 7),
	('minecraft_server_meta', 'survival-mode', 7),
	('minecraft_server_meta', 'adventure-mode', 7),

	('minecraft_server_community', 'adventure-mode', 7),
	('minecraft_server_community', 'smp', 7),
	('minecraft_server_community', 'mmo', 7),
	('minecraft_server_community', 'roleplay', 7),
	('minecraft_server_community', 'social', 7),
	('minecraft_server_community', 'creator-community', 7),
	('minecraft_server_community', 'recording-smp', 7),
	('minecraft_server_community', 'competitive', 7),
	('minecraft_server_community', 'technical', 7);
