CREATE TABLE user_locks (
	user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	locked_by BIGINT NOT NULL REFERENCES users(id),
	reason TEXT NOT NULL,
	created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
