use ariadne::ids::base62_id;

base62_id!(ChargeId);
base62_id!(CollectionId);
base62_id!(FileId);
base62_id!(ImageId);
base62_id!(NotificationId);
base62_id!(OAuthAccessTokenId);
base62_id!(OAuthClientAuthorizationId);
base62_id!(OAuthClientId);
base62_id!(OAuthRedirectUriId);
base62_id!(OrganizationId);
base62_id!(PatId);
base62_id!(PayoutId);
base62_id!(ProductId);
base62_id!(ProductPriceId);
base62_id!(ProjectId);
base62_id!(ReportId);
base62_id!(SessionId);
base62_id!(TeamId);
base62_id!(TeamMemberId);
base62_id!(ThreadId);
base62_id!(ThreadMessageId);
base62_id!(UserSubscriptionId);
base62_id!(VersionId);
