use super::{
    BOOL, SettingEditor, SupportedSetting, UNIT_INTERVAL, ValueEncoding,
    ranged_setting, setting, version_changes, versioned_setting,
};

const GRAPHICS: &[&str] = &["fast", "fancy", "fabulous", "custom"];
const AMBIENT_OCCLUSION: &[&str] = &["off", "on", "minimum", "maximum"];
const PARTICLES: &[&str] = &["0", "1", "2"];
const CLOUDS: &[&str] = &["false", "fast", "true"];
const ATTACK_INDICATOR: &[&str] = &["0", "1", "2"];
const INACTIVITY_FPS_LIMIT: &[&str] = &["afk", "minimized"];
const PRIORITIZE_CHUNK_UPDATES: &[&str] = &["0", "1", "2"];
const TEXTURE_FILTERING: &[&str] = &["0", "1", "2"];
const GRAPHICS_BACKEND: &[&str] = &["default", "opengl", "vulkan"];
const LEGACY_FPS_LIMIT: &[&str] = &["0", "1", "2"];
const LEGACY_VIEW_DISTANCE: &[&str] = &["0", "1", "2", "3"];

pub(super) const SETTINGS: &[SupportedSetting] = &[
    versioned_setting(
        "fov",
        &["fov"],
        version_changes::FOV_KEYS,
        "video",
        true,
        SettingEditor::Integer {
            min: 30,
            max: 110,
            step: 1,
        },
        ValueEncoding::Fov,
    ),
    versioned_setting(
        "graphics",
        &["graphicsPreset", "graphicsMode", "fancyGraphics"],
        version_changes::GRAPHICS_KEYS,
        "video",
        true,
        SettingEditor::Enum(GRAPHICS),
        ValueEncoding::Graphics,
    ),
    versioned_setting(
        "ambient_occlusion",
        &["ao"],
        version_changes::AMBIENT_OCCLUSION_KEYS,
        "video",
        true,
        SettingEditor::Enum(AMBIENT_OCCLUSION),
        ValueEncoding::AmbientOcclusion,
    ),
    setting(
        "brightness",
        &["gamma"],
        "video",
        true,
        UNIT_INTERVAL,
        ValueEncoding::Decimal,
    ),
    ranged_setting(
        "render_distance",
        &["renderDistance"],
        "1.7.2",
        "26.3",
        "video",
        false,
        SettingEditor::Integer {
            min: 2,
            max: 64,
            step: 1,
        },
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "legacy_view_distance",
        &["viewDistance"],
        "1.0",
        "1.6.4",
        "video",
        false,
        SettingEditor::Enum(LEGACY_VIEW_DISTANCE),
        ValueEncoding::Enum(LEGACY_VIEW_DISTANCE),
    ),
    ranged_setting(
        "simulation_distance",
        &["simulationDistance"],
        "1.18",
        "26.3",
        "video",
        false,
        SettingEditor::Integer {
            min: 2,
            max: 64,
            step: 1,
        },
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "entity_distance",
        &["entityDistanceScaling"],
        "1.16",
        "26.3",
        "video",
        false,
        SettingEditor::Decimal {
            min: 0.5,
            max: 5.0,
            step: 0.25,
            unit: Some("multiplier"),
        },
        ValueEncoding::Decimal,
    ),
    setting(
        "gui_scale",
        &["guiScale"],
        "video",
        true,
        SettingEditor::Integer {
            min: 0,
            max: 8,
            step: 1,
        },
        ValueEncoding::GuiScale,
    ),
    ranged_setting(
        "debug_gui_scale",
        &["debugGuiScale"],
        "26.3",
        "26.3",
        "video",
        true,
        SettingEditor::UnboundedInteger,
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "graphics_backend",
        &["preferredGraphicsBackend"],
        "26.2",
        "26.3",
        "video",
        false,
        SettingEditor::Enum(GRAPHICS_BACKEND),
        ValueEncoding::QuotedEnum(GRAPHICS_BACKEND),
    ),
    setting(
        "particles",
        &["particles"],
        "video",
        true,
        SettingEditor::Enum(PARTICLES),
        ValueEncoding::Enum(PARTICLES),
    ),
    versioned_setting(
        "clouds",
        &["renderClouds", "clouds"],
        version_changes::CLOUD_KEYS,
        "video",
        true,
        SettingEditor::Enum(CLOUDS),
        ValueEncoding::Clouds,
    ),
    ranged_setting(
        "cloud_range",
        &["cloudRange"],
        "1.21.6",
        "26.3",
        "video",
        false,
        SettingEditor::UnboundedInteger,
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "entity_shadows",
        &["entityShadows"],
        "1.8.1",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    setting(
        "view_bobbing",
        &["bobView"],
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "vsync",
        &["enableVsync"],
        "1.3.1",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "fullscreen",
        &["fullscreen"],
        "1.3.1",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "exclusive_fullscreen",
        &["exclusiveFullscreen"],
        "26.1",
        "26.3",
        "video",
        false,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "mac_fullscreen_menu",
        &["macFullscreenMenuVisibility"],
        "26.3",
        "26.3",
        "video",
        false,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "max_framerate",
        &["maxFps"],
        "1.7.2",
        "26.3",
        "video",
        true,
        SettingEditor::Integer {
            min: 10,
            max: 260,
            step: 10,
        },
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "legacy_framerate_limit",
        &["fpsLimit"],
        "1.0",
        "1.6.4",
        "video",
        false,
        SettingEditor::Enum(LEGACY_FPS_LIMIT),
        ValueEncoding::Enum(LEGACY_FPS_LIMIT),
    ),
    ranged_setting(
        "inactivity_framerate_limit",
        &["inactivityFpsLimit"],
        "1.21.2",
        "26.3",
        "video",
        true,
        SettingEditor::Enum(INACTIVITY_FPS_LIMIT),
        ValueEncoding::QuotedEnum(INACTIVITY_FPS_LIMIT),
    ),
    ranged_setting(
        "mipmap_levels",
        &["mipmapLevels"],
        "1.7.2",
        "26.3",
        "video",
        false,
        SettingEditor::Integer {
            min: 0,
            max: 4,
            step: 1,
        },
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "biome_blend_radius",
        &["biomeBlendRadius"],
        "1.13",
        "26.3",
        "video",
        true,
        SettingEditor::Integer {
            min: 0,
            max: 7,
            step: 1,
        },
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "prioritize_chunk_updates",
        &["prioritizeChunkUpdates"],
        "1.18",
        "26.3",
        "video",
        true,
        SettingEditor::Enum(PRIORITIZE_CHUNK_UPDATES),
        ValueEncoding::Enum(PRIORITIZE_CHUNK_UPDATES),
    ),
    ranged_setting(
        "attack_indicator",
        &["attackIndicator"],
        "1.9",
        "26.3",
        "video",
        true,
        SettingEditor::Enum(ATTACK_INDICATOR),
        ValueEncoding::Enum(ATTACK_INDICATOR),
    ),
    ranged_setting(
        "reduced_debug_info",
        &["reducedDebugInfo"],
        "1.8",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "chunk_fade_time",
        &["chunkSectionFadeInTime"],
        "1.21.11",
        "26.3",
        "video",
        false,
        SettingEditor::UnboundedDecimal,
        ValueEncoding::Decimal,
    ),
    ranged_setting(
        "cutout_leaves",
        &["cutoutLeaves"],
        "1.21.11",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "improved_transparency",
        &["improvedTransparency"],
        "1.21.11",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "texture_filtering",
        &["textureFiltering"],
        "1.21.11",
        "26.3",
        "video",
        false,
        SettingEditor::Enum(TEXTURE_FILTERING),
        ValueEncoding::Enum(TEXTURE_FILTERING),
    ),
    ranged_setting(
        "anisotropy",
        &["maxAnisotropyBit"],
        "1.21.11",
        "26.3",
        "video",
        false,
        SettingEditor::UnboundedInteger,
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "vignette",
        &["vignette"],
        "1.21.11",
        "26.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "weather_radius",
        &["weatherRadius"],
        "1.21.11",
        "26.3",
        "video",
        false,
        SettingEditor::UnboundedInteger,
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "advanced_opengl",
        &["advancedOpengl"],
        "1.0",
        "1.7.10",
        "video",
        false,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "anaglyph_3d",
        &["anaglyph3d"],
        "1.0",
        "1.12.2",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "anisotropic_filtering",
        &["anisotropicFiltering"],
        "1.7.2",
        "1.7.10",
        "video",
        false,
        SettingEditor::UnboundedInteger,
        ValueEncoding::Integer,
    ),
    ranged_setting(
        "alternate_blocks",
        &["allowBlockAlternatives"],
        "1.8",
        "1.8.9",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "held_item_tooltips",
        &["heldItemTooltips"],
        "1.4.6",
        "1.19.3",
        "video",
        true,
        BOOL,
        ValueEncoding::Bool,
    ),
    ranged_setting(
        "use_vbo",
        &["useVbo"],
        "1.8",
        "1.13.2",
        "video",
        false,
        BOOL,
        ValueEncoding::Bool,
    ),
];
