// Auto-generated icon imports and exports
// Do not edit this file manually - run 'pnpm run fix' to regenerate

import type { FunctionalComponent, SVGAttributes } from 'vue'

import _AffiliateIcon from './icons/affiliate.svg?component'
import _AlignLeftIcon from './icons/align-left.svg?component'
import _ArchiveIcon from './icons/archive.svg?component'
import _ArrowBigRightDashIcon from './icons/arrow-big-right-dash.svg?component'
import _ArrowBigUpDashIcon from './icons/arrow-big-up-dash.svg?component'
import _ArrowDownIcon from './icons/arrow-down.svg?component'
import _ArrowDownLeftIcon from './icons/arrow-down-left.svg?component'
import _ArrowLeftIcon from './icons/arrow-left.svg?component'
import _ArrowLeftRightIcon from './icons/arrow-left-right.svg?component'
import _ArrowUpIcon from './icons/arrow-up.svg?component'
import _ArrowUpRightIcon from './icons/arrow-up-right.svg?component'
import _AsteriskIcon from './icons/asterisk.svg?component'
import _BadgeCheckIcon from './icons/badge-check.svg?component'
import _BadgeDollarSignIcon from './icons/badge-dollar-sign.svg?component'
import _BanIcon from './icons/ban.svg?component'
import _BellIcon from './icons/bell.svg?component'
import _BellRingIcon from './icons/bell-ring.svg?component'
import _BlendIcon from './icons/blend.svg?component'
import _BlocksIcon from './icons/blocks.svg?component'
import _BoldIcon from './icons/bold.svg?component'
import _BookIcon from './icons/book.svg?component'
import _BookOpenIcon from './icons/book-open.svg?component'
import _BookTextIcon from './icons/book-text.svg?component'
import _BookmarkIcon from './icons/bookmark.svg?component'
import _BotIcon from './icons/bot.svg?component'
import _BoxIcon from './icons/box.svg?component'
import _BoxImportIcon from './icons/box-import.svg?component'
import _BoxesIcon from './icons/boxes.svg?component'
import _BracesIcon from './icons/braces.svg?component'
import _BrushCleaningIcon from './icons/brush-cleaning.svg?component'
import _BugIcon from './icons/bug.svg?component'
import _CalendarIcon from './icons/calendar.svg?component'
import _CardIcon from './icons/card.svg?component'
import _ChangeSkinIcon from './icons/change-skin.svg?component'
import _ChartIcon from './icons/chart.svg?component'
import _CheckIcon from './icons/check.svg?component'
import _CheckCheckIcon from './icons/check-check.svg?component'
import _CheckCircleIcon from './icons/check-circle.svg?component'
import _ChevronDownIcon from './icons/chevron-down.svg?component'
import _ChevronLeftIcon from './icons/chevron-left.svg?component'
import _ChevronRightIcon from './icons/chevron-right.svg?component'
import _ChevronUpIcon from './icons/chevron-up.svg?component'
import _CircleAlertIcon from './icons/circle-alert.svg?component'
import _CircleUserIcon from './icons/circle-user.svg?component'
import _ClearIcon from './icons/clear.svg?component'
import _ClientIcon from './icons/client.svg?component'
import _ClipboardCopyIcon from './icons/clipboard-copy.svg?component'
import _ClockIcon from './icons/clock.svg?component'
import _CloudIcon from './icons/cloud.svg?component'
import _CodeIcon from './icons/code.svg?component'
import _CoffeeIcon from './icons/coffee.svg?component'
import _CogIcon from './icons/cog.svg?component'
import _CoinsIcon from './icons/coins.svg?component'
import _CollapseIcon from './icons/collapse.svg?component'
import _CollectionIcon from './icons/collection.svg?component'
import _CompassIcon from './icons/compass.svg?component'
import _ContractIcon from './icons/contract.svg?component'
import _CopyIcon from './icons/copy.svg?component'
import _CopyrightIcon from './icons/copyright.svg?component'
import _CpuIcon from './icons/cpu.svg?component'
import _CrownIcon from './icons/crown.svg?component'
import _CubeIcon from './icons/cube.svg?component'
import _CurrencyIcon from './icons/currency.svg?component'
import _DashboardIcon from './icons/dashboard.svg?component'
import _DatabaseIcon from './icons/database.svg?component'
import _DatabaseBackupIcon from './icons/database-backup.svg?component'
import _DownloadIcon from './icons/download.svg?component'
import _DropdownIcon from './icons/dropdown.svg?component'
import _EditIcon from './icons/edit.svg?component'
import _EllipsisVerticalIcon from './icons/ellipsis-vertical.svg?component'
import _ExpandIcon from './icons/expand.svg?component'
import _ExternalIcon from './icons/external.svg?component'
import _EyeIcon from './icons/eye.svg?component'
import _EyeOffIcon from './icons/eye-off.svg?component'
import _FileIcon from './icons/file.svg?component'
import _FileArchiveIcon from './icons/file-archive.svg?component'
import _FileCodeIcon from './icons/file-code.svg?component'
import _FileImageIcon from './icons/file-image.svg?component'
import _FilePlusIcon from './icons/file-plus.svg?component'
import _FileTextIcon from './icons/file-text.svg?component'
import _FilterIcon from './icons/filter.svg?component'
import _FilterXIcon from './icons/filter-x.svg?component'
import _FolderIcon from './icons/folder.svg?component'
import _FolderArchiveIcon from './icons/folder-archive.svg?component'
import _FolderCogIcon from './icons/folder-cog.svg?component'
import _FolderOpenIcon from './icons/folder-open.svg?component'
import _FolderSearchIcon from './icons/folder-search.svg?component'
import _FolderUpIcon from './icons/folder-up.svg?component'
import _GameIcon from './icons/game.svg?component'
import _GapIcon from './icons/gap.svg?component'
import _GaugeIcon from './icons/gauge.svg?component'
import _GenericListIcon from './icons/generic-list.svg?component'
import _GiftIcon from './icons/gift.svg?component'
import _GitGraphIcon from './icons/git-graph.svg?component'
import _GlassesIcon from './icons/glasses.svg?component'
import _GlobeIcon from './icons/globe.svg?component'
import _GridIcon from './icons/grid.svg?component'
import _HamburgerIcon from './icons/hamburger.svg?component'
import _HammerIcon from './icons/hammer.svg?component'
import _HandHelpingIcon from './icons/hand-helping.svg?component'
import _HashIcon from './icons/hash.svg?component'
import _Heading1Icon from './icons/heading-1.svg?component'
import _Heading2Icon from './icons/heading-2.svg?component'
import _Heading3Icon from './icons/heading-3.svg?component'
import _HeartIcon from './icons/heart.svg?component'
import _HeartHandshakeIcon from './icons/heart-handshake.svg?component'
import _HeartMinusIcon from './icons/heart-minus.svg?component'
import _HistoryIcon from './icons/history.svg?component'
import _HomeIcon from './icons/home.svg?component'
import _ImageIcon from './icons/image.svg?component'
import _ImportIcon from './icons/import.svg?component'
import _InProgressIcon from './icons/in-progress.svg?component'
import _InfoIcon from './icons/info.svg?component'
import _IssuesIcon from './icons/issues.svg?component'
import _ItalicIcon from './icons/italic.svg?component'
import _KeyIcon from './icons/key.svg?component'
import _KeyboardIcon from './icons/keyboard.svg?component'
import _LandmarkIcon from './icons/landmark.svg?component'
import _LanguagesIcon from './icons/languages.svg?component'
import _LayoutTemplateIcon from './icons/layout-template.svg?component'
import _LeftArrowIcon from './icons/left-arrow.svg?component'
import _LibraryIcon from './icons/library.svg?component'
import _LightBulbIcon from './icons/light-bulb.svg?component'
import _LinkIcon from './icons/link.svg?component'
import _ListIcon from './icons/list.svg?component'
import _ListBulletedIcon from './icons/list-bulleted.svg?component'
import _ListEndIcon from './icons/list-end.svg?component'
import _ListFilterIcon from './icons/list-filter.svg?component'
import _ListOrderedIcon from './icons/list-ordered.svg?component'
import _LoaderIcon from './icons/loader.svg?component'
import _LoaderCircleIcon from './icons/loader-circle.svg?component'
import _LockIcon from './icons/lock.svg?component'
import _LockOpenIcon from './icons/lock-open.svg?component'
import _LogInIcon from './icons/log-in.svg?component'
import _LogOutIcon from './icons/log-out.svg?component'
import _MailIcon from './icons/mail.svg?component'
import _ManageIcon from './icons/manage.svg?component'
import _MaximizeIcon from './icons/maximize.svg?component'
import _MemoryStickIcon from './icons/memory-stick.svg?component'
import _MessageIcon from './icons/message.svg?component'
import _MicrophoneIcon from './icons/microphone.svg?component'
import _MinimizeIcon from './icons/minimize.svg?component'
import _MinusIcon from './icons/minus.svg?component'
import _MonitorIcon from './icons/monitor.svg?component'
import _MonitorSmartphoneIcon from './icons/monitor-smartphone.svg?component'
import _MoonIcon from './icons/moon.svg?component'
import _MoreHorizontalIcon from './icons/more-horizontal.svg?component'
import _MoreVerticalIcon from './icons/more-vertical.svg?component'
import _NewspaperIcon from './icons/newspaper.svg?component'
import _NoSignalIcon from './icons/no-signal.svg?component'
import _NotepadTextIcon from './icons/notepad-text.svg?component'
import _OmorphiaIcon from './icons/omorphia.svg?component'
import _OrganizationIcon from './icons/organization.svg?component'
import _PackageIcon from './icons/package.svg?component'
import _PackageClosedIcon from './icons/package-closed.svg?component'
import _PackageOpenIcon from './icons/package-open.svg?component'
import _PaintbrushIcon from './icons/paintbrush.svg?component'
import _PaletteIcon from './icons/palette.svg?component'
import _PickaxeIcon from './icons/pickaxe.svg?component'
import _PlayIcon from './icons/play.svg?component'
import _PlugIcon from './icons/plug.svg?component'
import _PlusIcon from './icons/plus.svg?component'
import _PowerIcon from './icons/power.svg?component'
import _PowerOffIcon from './icons/power-off.svg?component'
import _RadioButtonIcon from './icons/radio-button.svg?component'
import _RadioButtonCheckedIcon from './icons/radio-button-checked.svg?component'
import _ReceiptTextIcon from './icons/receipt-text.svg?component'
import _RedoIcon from './icons/redo.svg?component'
import _RefreshCwIcon from './icons/refresh-cw.svg?component'
import _ReplyIcon from './icons/reply.svg?component'
import _ReportIcon from './icons/report.svg?component'
import _RestoreIcon from './icons/restore.svg?component'
import _RightArrowIcon from './icons/right-arrow.svg?component'
import _RocketIcon from './icons/rocket.svg?component'
import _RotateClockwiseIcon from './icons/rotate-clockwise.svg?component'
import _RotateCounterClockwiseIcon from './icons/rotate-counter-clockwise.svg?component'
import _RssIcon from './icons/rss.svg?component'
import _SaveIcon from './icons/save.svg?component'
import _ScaleIcon from './icons/scale.svg?component'
import _ScanEyeIcon from './icons/scan-eye.svg?component'
import _SearchIcon from './icons/search.svg?component'
import _SendIcon from './icons/send.svg?component'
import _ServerIcon from './icons/server.svg?component'
import _ServerPlusIcon from './icons/server-plus.svg?component'
import _SettingsIcon from './icons/settings.svg?component'
import _ShareIcon from './icons/share.svg?component'
import _ShieldIcon from './icons/shield.svg?component'
import _ShieldAlertIcon from './icons/shield-alert.svg?component'
import _ShieldCheckIcon from './icons/shield-check.svg?component'
import _SignalIcon from './icons/signal.svg?component'
import _SkullIcon from './icons/skull.svg?component'
import _SlashIcon from './icons/slash.svg?component'
import _SortAscIcon from './icons/sort-asc.svg?component'
import _SortDescIcon from './icons/sort-desc.svg?component'
import _SparklesIcon from './icons/sparkles.svg?component'
import _SpinnerIcon from './icons/spinner.svg?component'
import _StarIcon from './icons/star.svg?component'
import _StopCircleIcon from './icons/stop-circle.svg?component'
import _StrikethroughIcon from './icons/strikethrough.svg?component'
import _SunIcon from './icons/sun.svg?component'
import _SunriseIcon from './icons/sunrise.svg?component'
import _SupportChatIcon from './icons/support-chat.svg?component'
import _TagIcon from './icons/tag.svg?component'
import _TagsIcon from './icons/tags.svg?component'
import _TagCategoryAdventureIcon from './icons/tags/categories/adventure.svg?component'
import _TagCategoryAtmosphereIcon from './icons/tags/categories/atmosphere.svg?component'
import _TagCategoryAudioIcon from './icons/tags/categories/audio.svg?component'
import _TagCategoryBlocksIcon from './icons/tags/categories/blocks.svg?component'
import _TagCategoryBloomIcon from './icons/tags/categories/bloom.svg?component'
import _TagCategoryCartoonIcon from './icons/tags/categories/cartoon.svg?component'
import _TagCategoryChallengingIcon from './icons/tags/categories/challenging.svg?component'
import _TagCategoryColoredLightingIcon from './icons/tags/categories/colored-lighting.svg?component'
import _TagCategoryCombatIcon from './icons/tags/categories/combat.svg?component'
import _TagCategoryCoreShadersIcon from './icons/tags/categories/core-shaders.svg?component'
import _TagCategoryCursedIcon from './icons/tags/categories/cursed.svg?component'
import _TagCategoryDecorationIcon from './icons/tags/categories/decoration.svg?component'
import _TagCategoryEconomyIcon from './icons/tags/categories/economy.svg?component'
import _TagCategoryEntitiesIcon from './icons/tags/categories/entities.svg?component'
import _TagCategoryEnvironmentIcon from './icons/tags/categories/environment.svg?component'
import _TagCategoryEquipmentIcon from './icons/tags/categories/equipment.svg?component'
import _TagCategoryFantasyIcon from './icons/tags/categories/fantasy.svg?component'
import _TagCategoryFoliageIcon from './icons/tags/categories/foliage.svg?component'
import _TagCategoryFontsIcon from './icons/tags/categories/fonts.svg?component'
import _TagCategoryFoodIcon from './icons/tags/categories/food.svg?component'
import _TagCategoryGameMechanicsIcon from './icons/tags/categories/game-mechanics.svg?component'
import _TagCategoryGuiIcon from './icons/tags/categories/gui.svg?component'
import _TagCategoryHighIcon from './icons/tags/categories/high.svg?component'
import _TagCategoryItemsIcon from './icons/tags/categories/items.svg?component'
import _TagCategoryKitchenSinkIcon from './icons/tags/categories/kitchen-sink.svg?component'
import _TagCategoryLibraryIcon from './icons/tags/categories/library.svg?component'
import _TagCategoryLightweightIcon from './icons/tags/categories/lightweight.svg?component'
import _TagCategoryLocaleIcon from './icons/tags/categories/locale.svg?component'
import _TagCategoryLowIcon from './icons/tags/categories/low.svg?component'
import _TagCategoryMagicIcon from './icons/tags/categories/magic.svg?component'
import _TagCategoryManagementIcon from './icons/tags/categories/management.svg?component'
import _TagCategoryMediumIcon from './icons/tags/categories/medium.svg?component'
import _TagCategoryMinigameIcon from './icons/tags/categories/minigame.svg?component'
import _TagCategoryMobsIcon from './icons/tags/categories/mobs.svg?component'
import _TagCategoryModdedIcon from './icons/tags/categories/modded.svg?component'
import _TagCategoryModelsIcon from './icons/tags/categories/models.svg?component'
import _TagCategoryMultiplayerIcon from './icons/tags/categories/multiplayer.svg?component'
import _TagCategoryOptimizationIcon from './icons/tags/categories/optimization.svg?component'
import _TagCategoryPathTracingIcon from './icons/tags/categories/path-tracing.svg?component'
import _TagCategoryPbrIcon from './icons/tags/categories/pbr.svg?component'
import _TagCategoryPotatoIcon from './icons/tags/categories/potato.svg?component'
import _TagCategoryQuestsIcon from './icons/tags/categories/quests.svg?component'
import _TagCategoryRealisticIcon from './icons/tags/categories/realistic.svg?component'
import _TagCategoryReflectionsIcon from './icons/tags/categories/reflections.svg?component'
import _TagCategoryScreenshotIcon from './icons/tags/categories/screenshot.svg?component'
import _TagCategorySemiRealisticIcon from './icons/tags/categories/semi-realistic.svg?component'
import _TagCategoryShadowsIcon from './icons/tags/categories/shadows.svg?component'
import _TagCategorySimplisticIcon from './icons/tags/categories/simplistic.svg?component'
import _TagCategorySocialIcon from './icons/tags/categories/social.svg?component'
import _TagCategoryStorageIcon from './icons/tags/categories/storage.svg?component'
import _TagCategoryTechnologyIcon from './icons/tags/categories/technology.svg?component'
import _TagCategoryThemedIcon from './icons/tags/categories/themed.svg?component'
import _TagCategoryTransportationIcon from './icons/tags/categories/transportation.svg?component'
import _TagCategoryTweaksIcon from './icons/tags/categories/tweaks.svg?component'
import _TagCategoryUtilityIcon from './icons/tags/categories/utility.svg?component'
import _TagCategoryVanillaLikeIcon from './icons/tags/categories/vanilla-like.svg?component'
import _TagCategoryWorldgenIcon from './icons/tags/categories/worldgen.svg?component'
import _TagLoaderBabricIcon from './icons/tags/loaders/babric.svg?component'
import _TagLoaderBtaBabricIcon from './icons/tags/loaders/bta-babric.svg?component'
import _TagLoaderBukkitIcon from './icons/tags/loaders/bukkit.svg?component'
import _TagLoaderBungeecordIcon from './icons/tags/loaders/bungeecord.svg?component'
import _TagLoaderCanvasIcon from './icons/tags/loaders/canvas.svg?component'
import _TagLoaderDatapackIcon from './icons/tags/loaders/datapack.svg?component'
import _TagLoaderFabricIcon from './icons/tags/loaders/fabric.svg?component'
import _TagLoaderFoliaIcon from './icons/tags/loaders/folia.svg?component'
import _TagLoaderForgeIcon from './icons/tags/loaders/forge.svg?component'
import _TagLoaderGeyserIcon from './icons/tags/loaders/geyser.svg?component'
import _TagLoaderIrisIcon from './icons/tags/loaders/iris.svg?component'
import _TagLoaderJavaAgentIcon from './icons/tags/loaders/java-agent.svg?component'
import _TagLoaderLegacyFabricIcon from './icons/tags/loaders/legacy-fabric.svg?component'
import _TagLoaderLiteloaderIcon from './icons/tags/loaders/liteloader.svg?component'
import _TagLoaderMinecraftIcon from './icons/tags/loaders/minecraft.svg?component'
import _TagLoaderModloaderIcon from './icons/tags/loaders/modloader.svg?component'
import _TagLoaderMrpackIcon from './icons/tags/loaders/mrpack.svg?component'
import _TagLoaderNeoforgeIcon from './icons/tags/loaders/neoforge.svg?component'
import _TagLoaderNilloaderIcon from './icons/tags/loaders/nilloader.svg?component'
import _TagLoaderOptifineIcon from './icons/tags/loaders/optifine.svg?component'
import _TagLoaderOrnitheIcon from './icons/tags/loaders/ornithe.svg?component'
import _TagLoaderPaperIcon from './icons/tags/loaders/paper.svg?component'
import _TagLoaderPurpurIcon from './icons/tags/loaders/purpur.svg?component'
import _TagLoaderQuiltIcon from './icons/tags/loaders/quilt.svg?component'
import _TagLoaderRiftIcon from './icons/tags/loaders/rift.svg?component'
import _TagLoaderSpigotIcon from './icons/tags/loaders/spigot.svg?component'
import _TagLoaderSpongeIcon from './icons/tags/loaders/sponge.svg?component'
import _TagLoaderVanillaIcon from './icons/tags/loaders/vanilla.svg?component'
import _TagLoaderVelocityIcon from './icons/tags/loaders/velocity.svg?component'
import _TagLoaderWaterfallIcon from './icons/tags/loaders/waterfall.svg?component'
import _TerminalSquareIcon from './icons/terminal-square.svg?component'
import _TestIcon from './icons/test.svg?component'
import _TextCursorInputIcon from './icons/text-cursor-input.svg?component'
import _TextQuoteIcon from './icons/text-quote.svg?component'
import _TimerIcon from './icons/timer.svg?component'
import _ToggleLeftIcon from './icons/toggle-left.svg?component'
import _ToggleRightIcon from './icons/toggle-right.svg?component'
import _TransferIcon from './icons/transfer.svg?component'
import _TrashIcon from './icons/trash.svg?component'
import _TriangleAlertIcon from './icons/triangle-alert.svg?component'
import _UnderlineIcon from './icons/underline.svg?component'
import _UndoIcon from './icons/undo.svg?component'
import _UnknownIcon from './icons/unknown.svg?component'
import _UnknownDonationIcon from './icons/unknown-donation.svg?component'
import _UnlinkIcon from './icons/unlink.svg?component'
import _UnplugIcon from './icons/unplug.svg?component'
import _UpdatedIcon from './icons/updated.svg?component'
import _UploadIcon from './icons/upload.svg?component'
import _UserIcon from './icons/user.svg?component'
import _UserCogIcon from './icons/user-cog.svg?component'
import _UserPlusIcon from './icons/user-plus.svg?component'
import _UserRoundIcon from './icons/user-round.svg?component'
import _UserSearchIcon from './icons/user-search.svg?component'
import _UserXIcon from './icons/user-x.svg?component'
import _UsersIcon from './icons/users.svg?component'
import _VersionIcon from './icons/version.svg?component'
import _WikiIcon from './icons/wiki.svg?component'
import _WindowIcon from './icons/window.svg?component'
import _WorldIcon from './icons/world.svg?component'
import _WrenchIcon from './icons/wrench.svg?component'
import _XIcon from './icons/x.svg?component'
import _XCircleIcon from './icons/x-circle.svg?component'
import _ZoomInIcon from './icons/zoom-in.svg?component'
import _ZoomOutIcon from './icons/zoom-out.svg?component'

export type IconComponent = FunctionalComponent<SVGAttributes>

export const AffiliateIcon = _AffiliateIcon
export const AlignLeftIcon = _AlignLeftIcon
export const ArchiveIcon = _ArchiveIcon
export const ArrowBigRightDashIcon = _ArrowBigRightDashIcon
export const ArrowBigUpDashIcon = _ArrowBigUpDashIcon
export const ArrowDownIcon = _ArrowDownIcon
export const ArrowDownLeftIcon = _ArrowDownLeftIcon
export const ArrowLeftIcon = _ArrowLeftIcon
export const ArrowLeftRightIcon = _ArrowLeftRightIcon
export const ArrowUpIcon = _ArrowUpIcon
export const ArrowUpRightIcon = _ArrowUpRightIcon
export const AsteriskIcon = _AsteriskIcon
export const BadgeCheckIcon = _BadgeCheckIcon
export const BadgeDollarSignIcon = _BadgeDollarSignIcon
export const BanIcon = _BanIcon
export const BellIcon = _BellIcon
export const BellRingIcon = _BellRingIcon
export const BlendIcon = _BlendIcon
export const BlocksIcon = _BlocksIcon
export const BoldIcon = _BoldIcon
export const BookIcon = _BookIcon
export const BookOpenIcon = _BookOpenIcon
export const BookTextIcon = _BookTextIcon
export const BookmarkIcon = _BookmarkIcon
export const BotIcon = _BotIcon
export const BoxIcon = _BoxIcon
export const BoxImportIcon = _BoxImportIcon
export const BoxesIcon = _BoxesIcon
export const BracesIcon = _BracesIcon
export const BrushCleaningIcon = _BrushCleaningIcon
export const BugIcon = _BugIcon
export const CalendarIcon = _CalendarIcon
export const CardIcon = _CardIcon
export const ChangeSkinIcon = _ChangeSkinIcon
export const ChartIcon = _ChartIcon
export const CheckIcon = _CheckIcon
export const CheckCheckIcon = _CheckCheckIcon
export const CheckCircleIcon = _CheckCircleIcon
export const ChevronDownIcon = _ChevronDownIcon
export const ChevronLeftIcon = _ChevronLeftIcon
export const ChevronRightIcon = _ChevronRightIcon
export const ChevronUpIcon = _ChevronUpIcon
export const CircleAlertIcon = _CircleAlertIcon
export const CircleUserIcon = _CircleUserIcon
export const ClearIcon = _ClearIcon
export const ClientIcon = _ClientIcon
export const ClipboardCopyIcon = _ClipboardCopyIcon
export const ClockIcon = _ClockIcon
export const CloudIcon = _CloudIcon
export const CodeIcon = _CodeIcon
export const CoffeeIcon = _CoffeeIcon
export const CogIcon = _CogIcon
export const CoinsIcon = _CoinsIcon
export const CollapseIcon = _CollapseIcon
export const CollectionIcon = _CollectionIcon
export const CompassIcon = _CompassIcon
export const ContractIcon = _ContractIcon
export const CopyIcon = _CopyIcon
export const CopyrightIcon = _CopyrightIcon
export const CpuIcon = _CpuIcon
export const CrownIcon = _CrownIcon
export const CubeIcon = _CubeIcon
export const CurrencyIcon = _CurrencyIcon
export const DashboardIcon = _DashboardIcon
export const DatabaseIcon = _DatabaseIcon
export const DatabaseBackupIcon = _DatabaseBackupIcon
export const DownloadIcon = _DownloadIcon
export const DropdownIcon = _DropdownIcon
export const EditIcon = _EditIcon
export const EllipsisVerticalIcon = _EllipsisVerticalIcon
export const ExpandIcon = _ExpandIcon
export const ExternalIcon = _ExternalIcon
export const EyeIcon = _EyeIcon
export const EyeOffIcon = _EyeOffIcon
export const FileIcon = _FileIcon
export const FileArchiveIcon = _FileArchiveIcon
export const FileCodeIcon = _FileCodeIcon
export const FileImageIcon = _FileImageIcon
export const FilePlusIcon = _FilePlusIcon
export const FileTextIcon = _FileTextIcon
export const FilterIcon = _FilterIcon
export const FilterXIcon = _FilterXIcon
export const FolderIcon = _FolderIcon
export const FolderArchiveIcon = _FolderArchiveIcon
export const FolderCogIcon = _FolderCogIcon
export const FolderOpenIcon = _FolderOpenIcon
export const FolderSearchIcon = _FolderSearchIcon
export const FolderUpIcon = _FolderUpIcon
export const GameIcon = _GameIcon
export const GapIcon = _GapIcon
export const GaugeIcon = _GaugeIcon
export const GenericListIcon = _GenericListIcon
export const GiftIcon = _GiftIcon
export const GitGraphIcon = _GitGraphIcon
export const GlassesIcon = _GlassesIcon
export const GlobeIcon = _GlobeIcon
export const GridIcon = _GridIcon
export const HamburgerIcon = _HamburgerIcon
export const HammerIcon = _HammerIcon
export const HandHelpingIcon = _HandHelpingIcon
export const HashIcon = _HashIcon
export const Heading1Icon = _Heading1Icon
export const Heading2Icon = _Heading2Icon
export const Heading3Icon = _Heading3Icon
export const HeartIcon = _HeartIcon
export const HeartHandshakeIcon = _HeartHandshakeIcon
export const HeartMinusIcon = _HeartMinusIcon
export const HistoryIcon = _HistoryIcon
export const HomeIcon = _HomeIcon
export const ImageIcon = _ImageIcon
export const ImportIcon = _ImportIcon
export const InProgressIcon = _InProgressIcon
export const InfoIcon = _InfoIcon
export const IssuesIcon = _IssuesIcon
export const ItalicIcon = _ItalicIcon
export const KeyIcon = _KeyIcon
export const KeyboardIcon = _KeyboardIcon
export const LandmarkIcon = _LandmarkIcon
export const LanguagesIcon = _LanguagesIcon
export const LayoutTemplateIcon = _LayoutTemplateIcon
export const LeftArrowIcon = _LeftArrowIcon
export const LibraryIcon = _LibraryIcon
export const LightBulbIcon = _LightBulbIcon
export const LinkIcon = _LinkIcon
export const ListIcon = _ListIcon
export const ListBulletedIcon = _ListBulletedIcon
export const ListEndIcon = _ListEndIcon
export const ListFilterIcon = _ListFilterIcon
export const ListOrderedIcon = _ListOrderedIcon
export const LoaderIcon = _LoaderIcon
export const LoaderCircleIcon = _LoaderCircleIcon
export const LockIcon = _LockIcon
export const LockOpenIcon = _LockOpenIcon
export const LogInIcon = _LogInIcon
export const LogOutIcon = _LogOutIcon
export const MailIcon = _MailIcon
export const ManageIcon = _ManageIcon
export const MaximizeIcon = _MaximizeIcon
export const MemoryStickIcon = _MemoryStickIcon
export const MessageIcon = _MessageIcon
export const MicrophoneIcon = _MicrophoneIcon
export const MinimizeIcon = _MinimizeIcon
export const MinusIcon = _MinusIcon
export const MonitorIcon = _MonitorIcon
export const MonitorSmartphoneIcon = _MonitorSmartphoneIcon
export const MoonIcon = _MoonIcon
export const MoreHorizontalIcon = _MoreHorizontalIcon
export const MoreVerticalIcon = _MoreVerticalIcon
export const NewspaperIcon = _NewspaperIcon
export const NoSignalIcon = _NoSignalIcon
export const NotepadTextIcon = _NotepadTextIcon
export const OmorphiaIcon = _OmorphiaIcon
export const OrganizationIcon = _OrganizationIcon
export const PackageIcon = _PackageIcon
export const PackageClosedIcon = _PackageClosedIcon
export const PackageOpenIcon = _PackageOpenIcon
export const PaintbrushIcon = _PaintbrushIcon
export const PaletteIcon = _PaletteIcon
export const PickaxeIcon = _PickaxeIcon
export const PlayIcon = _PlayIcon
export const PlugIcon = _PlugIcon
export const PlusIcon = _PlusIcon
export const PowerIcon = _PowerIcon
export const PowerOffIcon = _PowerOffIcon
export const RadioButtonIcon = _RadioButtonIcon
export const RadioButtonCheckedIcon = _RadioButtonCheckedIcon
export const ReceiptTextIcon = _ReceiptTextIcon
export const RedoIcon = _RedoIcon
export const RefreshCwIcon = _RefreshCwIcon
export const ReplyIcon = _ReplyIcon
export const ReportIcon = _ReportIcon
export const RestoreIcon = _RestoreIcon
export const RightArrowIcon = _RightArrowIcon
export const RocketIcon = _RocketIcon
export const RotateClockwiseIcon = _RotateClockwiseIcon
export const RotateCounterClockwiseIcon = _RotateCounterClockwiseIcon
export const RssIcon = _RssIcon
export const SaveIcon = _SaveIcon
export const ScaleIcon = _ScaleIcon
export const ScanEyeIcon = _ScanEyeIcon
export const SearchIcon = _SearchIcon
export const SendIcon = _SendIcon
export const ServerIcon = _ServerIcon
export const ServerPlusIcon = _ServerPlusIcon
export const SettingsIcon = _SettingsIcon
export const ShareIcon = _ShareIcon
export const ShieldIcon = _ShieldIcon
export const ShieldAlertIcon = _ShieldAlertIcon
export const ShieldCheckIcon = _ShieldCheckIcon
export const SignalIcon = _SignalIcon
export const SkullIcon = _SkullIcon
export const SlashIcon = _SlashIcon
export const SortAscIcon = _SortAscIcon
export const SortDescIcon = _SortDescIcon
export const SparklesIcon = _SparklesIcon
export const SpinnerIcon = _SpinnerIcon
export const StarIcon = _StarIcon
export const StopCircleIcon = _StopCircleIcon
export const StrikethroughIcon = _StrikethroughIcon
export const SunIcon = _SunIcon
export const SunriseIcon = _SunriseIcon
export const SupportChatIcon = _SupportChatIcon
export const TagIcon = _TagIcon
export const TagsIcon = _TagsIcon
export const TagCategoryAdventureIcon = _TagCategoryAdventureIcon
export const TagCategoryAtmosphereIcon = _TagCategoryAtmosphereIcon
export const TagCategoryAudioIcon = _TagCategoryAudioIcon
export const TagCategoryBlocksIcon = _TagCategoryBlocksIcon
export const TagCategoryBloomIcon = _TagCategoryBloomIcon
export const TagCategoryCartoonIcon = _TagCategoryCartoonIcon
export const TagCategoryChallengingIcon = _TagCategoryChallengingIcon
export const TagCategoryColoredLightingIcon = _TagCategoryColoredLightingIcon
export const TagCategoryCombatIcon = _TagCategoryCombatIcon
export const TagCategoryCoreShadersIcon = _TagCategoryCoreShadersIcon
export const TagCategoryCursedIcon = _TagCategoryCursedIcon
export const TagCategoryDecorationIcon = _TagCategoryDecorationIcon
export const TagCategoryEconomyIcon = _TagCategoryEconomyIcon
export const TagCategoryEntitiesIcon = _TagCategoryEntitiesIcon
export const TagCategoryEnvironmentIcon = _TagCategoryEnvironmentIcon
export const TagCategoryEquipmentIcon = _TagCategoryEquipmentIcon
export const TagCategoryFantasyIcon = _TagCategoryFantasyIcon
export const TagCategoryFoliageIcon = _TagCategoryFoliageIcon
export const TagCategoryFontsIcon = _TagCategoryFontsIcon
export const TagCategoryFoodIcon = _TagCategoryFoodIcon
export const TagCategoryGameMechanicsIcon = _TagCategoryGameMechanicsIcon
export const TagCategoryGuiIcon = _TagCategoryGuiIcon
export const TagCategoryHighIcon = _TagCategoryHighIcon
export const TagCategoryItemsIcon = _TagCategoryItemsIcon
export const TagCategoryKitchenSinkIcon = _TagCategoryKitchenSinkIcon
export const TagCategoryLibraryIcon = _TagCategoryLibraryIcon
export const TagCategoryLightweightIcon = _TagCategoryLightweightIcon
export const TagCategoryLocaleIcon = _TagCategoryLocaleIcon
export const TagCategoryLowIcon = _TagCategoryLowIcon
export const TagCategoryMagicIcon = _TagCategoryMagicIcon
export const TagCategoryManagementIcon = _TagCategoryManagementIcon
export const TagCategoryMediumIcon = _TagCategoryMediumIcon
export const TagCategoryMinigameIcon = _TagCategoryMinigameIcon
export const TagCategoryMobsIcon = _TagCategoryMobsIcon
export const TagCategoryModdedIcon = _TagCategoryModdedIcon
export const TagCategoryModelsIcon = _TagCategoryModelsIcon
export const TagCategoryMultiplayerIcon = _TagCategoryMultiplayerIcon
export const TagCategoryOptimizationIcon = _TagCategoryOptimizationIcon
export const TagCategoryPathTracingIcon = _TagCategoryPathTracingIcon
export const TagCategoryPbrIcon = _TagCategoryPbrIcon
export const TagCategoryPotatoIcon = _TagCategoryPotatoIcon
export const TagCategoryQuestsIcon = _TagCategoryQuestsIcon
export const TagCategoryRealisticIcon = _TagCategoryRealisticIcon
export const TagCategoryReflectionsIcon = _TagCategoryReflectionsIcon
export const TagCategoryScreenshotIcon = _TagCategoryScreenshotIcon
export const TagCategorySemiRealisticIcon = _TagCategorySemiRealisticIcon
export const TagCategoryShadowsIcon = _TagCategoryShadowsIcon
export const TagCategorySimplisticIcon = _TagCategorySimplisticIcon
export const TagCategorySocialIcon = _TagCategorySocialIcon
export const TagCategoryStorageIcon = _TagCategoryStorageIcon
export const TagCategoryTechnologyIcon = _TagCategoryTechnologyIcon
export const TagCategoryThemedIcon = _TagCategoryThemedIcon
export const TagCategoryTransportationIcon = _TagCategoryTransportationIcon
export const TagCategoryTweaksIcon = _TagCategoryTweaksIcon
export const TagCategoryUtilityIcon = _TagCategoryUtilityIcon
export const TagCategoryVanillaLikeIcon = _TagCategoryVanillaLikeIcon
export const TagCategoryWorldgenIcon = _TagCategoryWorldgenIcon
export const TagLoaderBabricIcon = _TagLoaderBabricIcon
export const TagLoaderBtaBabricIcon = _TagLoaderBtaBabricIcon
export const TagLoaderBukkitIcon = _TagLoaderBukkitIcon
export const TagLoaderBungeecordIcon = _TagLoaderBungeecordIcon
export const TagLoaderCanvasIcon = _TagLoaderCanvasIcon
export const TagLoaderDatapackIcon = _TagLoaderDatapackIcon
export const TagLoaderFabricIcon = _TagLoaderFabricIcon
export const TagLoaderFoliaIcon = _TagLoaderFoliaIcon
export const TagLoaderForgeIcon = _TagLoaderForgeIcon
export const TagLoaderGeyserIcon = _TagLoaderGeyserIcon
export const TagLoaderIrisIcon = _TagLoaderIrisIcon
export const TagLoaderJavaAgentIcon = _TagLoaderJavaAgentIcon
export const TagLoaderLegacyFabricIcon = _TagLoaderLegacyFabricIcon
export const TagLoaderLiteloaderIcon = _TagLoaderLiteloaderIcon
export const TagLoaderMinecraftIcon = _TagLoaderMinecraftIcon
export const TagLoaderModloaderIcon = _TagLoaderModloaderIcon
export const TagLoaderMrpackIcon = _TagLoaderMrpackIcon
export const TagLoaderNeoforgeIcon = _TagLoaderNeoforgeIcon
export const TagLoaderNilloaderIcon = _TagLoaderNilloaderIcon
export const TagLoaderOptifineIcon = _TagLoaderOptifineIcon
export const TagLoaderOrnitheIcon = _TagLoaderOrnitheIcon
export const TagLoaderPaperIcon = _TagLoaderPaperIcon
export const TagLoaderPurpurIcon = _TagLoaderPurpurIcon
export const TagLoaderQuiltIcon = _TagLoaderQuiltIcon
export const TagLoaderRiftIcon = _TagLoaderRiftIcon
export const TagLoaderSpigotIcon = _TagLoaderSpigotIcon
export const TagLoaderSpongeIcon = _TagLoaderSpongeIcon
export const TagLoaderVanillaIcon = _TagLoaderVanillaIcon
export const TagLoaderVelocityIcon = _TagLoaderVelocityIcon
export const TagLoaderWaterfallIcon = _TagLoaderWaterfallIcon
export const TerminalSquareIcon = _TerminalSquareIcon
export const TestIcon = _TestIcon
export const TextCursorInputIcon = _TextCursorInputIcon
export const TextQuoteIcon = _TextQuoteIcon
export const TimerIcon = _TimerIcon
export const ToggleLeftIcon = _ToggleLeftIcon
export const ToggleRightIcon = _ToggleRightIcon
export const TransferIcon = _TransferIcon
export const TrashIcon = _TrashIcon
export const TriangleAlertIcon = _TriangleAlertIcon
export const UnderlineIcon = _UnderlineIcon
export const UndoIcon = _UndoIcon
export const UnknownIcon = _UnknownIcon
export const UnknownDonationIcon = _UnknownDonationIcon
export const UnlinkIcon = _UnlinkIcon
export const UnplugIcon = _UnplugIcon
export const UpdatedIcon = _UpdatedIcon
export const UploadIcon = _UploadIcon
export const UserIcon = _UserIcon
export const UserCogIcon = _UserCogIcon
export const UserPlusIcon = _UserPlusIcon
export const UserRoundIcon = _UserRoundIcon
export const UserSearchIcon = _UserSearchIcon
export const UserXIcon = _UserXIcon
export const UsersIcon = _UsersIcon
export const VersionIcon = _VersionIcon
export const WikiIcon = _WikiIcon
export const WindowIcon = _WindowIcon
export const WorldIcon = _WorldIcon
export const WrenchIcon = _WrenchIcon
export const XIcon = _XIcon
export const XCircleIcon = _XCircleIcon
export const ZoomInIcon = _ZoomInIcon
export const ZoomOutIcon = _ZoomOutIcon

export const categoryIconMap: Record<string, IconComponent> = {
	adventure: TagCategoryAdventureIcon,
	atmosphere: TagCategoryAtmosphereIcon,
	audio: TagCategoryAudioIcon,
	blocks: TagCategoryBlocksIcon,
	bloom: TagCategoryBloomIcon,
	cartoon: TagCategoryCartoonIcon,
	challenging: TagCategoryChallengingIcon,
	'colored-lighting': TagCategoryColoredLightingIcon,
	combat: TagCategoryCombatIcon,
	'core-shaders': TagCategoryCoreShadersIcon,
	cursed: TagCategoryCursedIcon,
	decoration: TagCategoryDecorationIcon,
	economy: TagCategoryEconomyIcon,
	entities: TagCategoryEntitiesIcon,
	environment: TagCategoryEnvironmentIcon,
	equipment: TagCategoryEquipmentIcon,
	fantasy: TagCategoryFantasyIcon,
	foliage: TagCategoryFoliageIcon,
	fonts: TagCategoryFontsIcon,
	food: TagCategoryFoodIcon,
	'game-mechanics': TagCategoryGameMechanicsIcon,
	gui: TagCategoryGuiIcon,
	high: TagCategoryHighIcon,
	items: TagCategoryItemsIcon,
	'kitchen-sink': TagCategoryKitchenSinkIcon,
	library: TagCategoryLibraryIcon,
	lightweight: TagCategoryLightweightIcon,
	locale: TagCategoryLocaleIcon,
	low: TagCategoryLowIcon,
	magic: TagCategoryMagicIcon,
	management: TagCategoryManagementIcon,
	medium: TagCategoryMediumIcon,
	minigame: TagCategoryMinigameIcon,
	mobs: TagCategoryMobsIcon,
	modded: TagCategoryModdedIcon,
	models: TagCategoryModelsIcon,
	multiplayer: TagCategoryMultiplayerIcon,
	optimization: TagCategoryOptimizationIcon,
	'path-tracing': TagCategoryPathTracingIcon,
	pbr: TagCategoryPbrIcon,
	potato: TagCategoryPotatoIcon,
	quests: TagCategoryQuestsIcon,
	realistic: TagCategoryRealisticIcon,
	reflections: TagCategoryReflectionsIcon,
	screenshot: TagCategoryScreenshotIcon,
	'semi-realistic': TagCategorySemiRealisticIcon,
	shadows: TagCategoryShadowsIcon,
	simplistic: TagCategorySimplisticIcon,
	social: TagCategorySocialIcon,
	storage: TagCategoryStorageIcon,
	technology: TagCategoryTechnologyIcon,
	themed: TagCategoryThemedIcon,
	transportation: TagCategoryTransportationIcon,
	tweaks: TagCategoryTweaksIcon,
	utility: TagCategoryUtilityIcon,
	'vanilla-like': TagCategoryVanillaLikeIcon,
	worldgen: TagCategoryWorldgenIcon,
}

export const loaderIconMap: Record<string, IconComponent> = {
	babric: TagLoaderBabricIcon,
	'bta-babric': TagLoaderBtaBabricIcon,
	bukkit: TagLoaderBukkitIcon,
	bungeecord: TagLoaderBungeecordIcon,
	canvas: TagLoaderCanvasIcon,
	datapack: TagLoaderDatapackIcon,
	fabric: TagLoaderFabricIcon,
	folia: TagLoaderFoliaIcon,
	forge: TagLoaderForgeIcon,
	geyser: TagLoaderGeyserIcon,
	iris: TagLoaderIrisIcon,
	'java-agent': TagLoaderJavaAgentIcon,
	'legacy-fabric': TagLoaderLegacyFabricIcon,
	liteloader: TagLoaderLiteloaderIcon,
	minecraft: TagLoaderMinecraftIcon,
	modloader: TagLoaderModloaderIcon,
	mrpack: TagLoaderMrpackIcon,
	neoforge: TagLoaderNeoforgeIcon,
	nilloader: TagLoaderNilloaderIcon,
	optifine: TagLoaderOptifineIcon,
	ornithe: TagLoaderOrnitheIcon,
	paper: TagLoaderPaperIcon,
	purpur: TagLoaderPurpurIcon,
	quilt: TagLoaderQuiltIcon,
	rift: TagLoaderRiftIcon,
	spigot: TagLoaderSpigotIcon,
	sponge: TagLoaderSpongeIcon,
	vanilla: TagLoaderVanillaIcon,
	velocity: TagLoaderVelocityIcon,
	waterfall: TagLoaderWaterfallIcon,
}
