#ifndef MODRINTH_SANDBOX_H
#define MODRINTH_SANDBOX_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define MODRINTH_SANDBOX_STDIO_NULL 0

#define MODRINTH_SANDBOX_STDIO_INHERIT 1

#define MODRINTH_SANDBOX_STDIO_PIPE 2

typedef struct ModrinthSandboxChild ModrinthSandboxChild;

typedef struct ModrinthSandboxCommand ModrinthSandboxCommand;

typedef struct ModrinthSandboxEnv ModrinthSandboxEnv;

typedef struct ModrinthSandboxPipeReader ModrinthSandboxPipeReader;

typedef struct ModrinthSandboxPipeWriter ModrinthSandboxPipeWriter;

/**
 * C representation of a sandboxed child's exit status.
 *
 * If `exited` is false, the other fields have no meaning. If `has_code` is
 * false, the process terminated without an exit code, such as from a signal.
 */
typedef struct ModrinthSandboxExitStatus {
  bool exited;
  bool success;
  bool has_code;
  int32_t code;
} ModrinthSandboxExitStatus;

typedef struct ModrinthSandboxString {
  const uint8_t *ptr;
  size_t len;
} ModrinthSandboxString;

typedef struct ModrinthSandboxStringSlice {
  const struct ModrinthSandboxString *ptr;
  size_t len;
} ModrinthSandboxStringSlice;

typedef struct ModrinthSandboxStringOption {
  const uint8_t *ptr;
  size_t len;
} ModrinthSandboxStringOption;

typedef struct ModrinthSandboxStringPairsSlice {
  const struct ModrinthSandboxString *key_ptr;
  size_t key_len;
  const struct ModrinthSandboxString *value_ptr;
  size_t value_len;
} ModrinthSandboxStringPairsSlice;

typedef struct ModrinthSandboxCommandView {
  struct ModrinthSandboxString executable;
  struct ModrinthSandboxStringSlice args;
  struct ModrinthSandboxStringSlice ensure_dirs_exist;
  struct ModrinthSandboxStringSlice read_only_paths;
  struct ModrinthSandboxStringSlice read_write_paths;
  struct ModrinthSandboxStringOption working_directory;
  struct ModrinthSandboxStringSlice passthrough_environment;
  struct ModrinthSandboxStringPairsSlice extra_environment;
  bool allow_network;
  bool is_jvm;
  bool die_with_parent;
  uint32_t child_stdin;
  uint32_t child_stdout;
  uint32_t child_stderr;
  struct ModrinthSandboxString app_container_name;
  struct ModrinthSandboxString app_container_description;
} ModrinthSandboxCommandView;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the child's platform process ID, or zero when no stable process ID
 * is available for this backend or the child has already exited.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`]. `out_id` must be properly
 * aligned and valid for writing one `u32`. Neither pointer may be concurrently
 * accessed for the duration of this call.
 */
bool modrinth_sandbox_child_id(const struct ModrinthSandboxChild *child, uint32_t *out_id);

/**
 * Attempts to collect the child's exit status without blocking.
 *
 * On success, `out_status.exited` is false when the child is still running.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call. `out_status` must be properly aligned and
 * valid for writing one [`ModrinthSandboxExitStatus`].
 */
bool modrinth_sandbox_child_try_wait(struct ModrinthSandboxChild *child,
                                     struct ModrinthSandboxExitStatus *out_status);

/**
 * Blocks until the child exits and writes its exit status.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call. `out_status` must be properly aligned and
 * valid for writing one [`ModrinthSandboxExitStatus`].
 */
bool modrinth_sandbox_child_wait(struct ModrinthSandboxChild *child,
                                 struct ModrinthSandboxExitStatus *out_status);

/**
 * Forces the child process to exit.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call.
 */
bool modrinth_sandbox_child_kill(struct ModrinthSandboxChild *child);

/**
 * Takes ownership of the child's standard-input pipe.
 *
 * On success, `*out_stdin` is null if stdin was not configured as a pipe or
 * was already taken.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call. `out_stdin` must be properly aligned and
 * valid for writing a `*mut ModrinthSandboxPipeWriter`, and must not contain an
 * owned handle.
 */
bool modrinth_sandbox_child_take_stdin(struct ModrinthSandboxChild *child,
                                       struct ModrinthSandboxPipeWriter **out_stdin);

/**
 * Takes ownership of the child's standard-output pipe.
 *
 * On success, `*out_stdout` is null if stdout was not configured as a pipe or
 * was already taken.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call. `out_stdout` must be properly aligned and
 * valid for writing a `*mut ModrinthSandboxPipeReader`, and must not contain an
 * owned handle.
 */
bool modrinth_sandbox_child_take_stdout(struct ModrinthSandboxChild *child,
                                        struct ModrinthSandboxPipeReader **out_stdout);

/**
 * Takes ownership of the child's standard-error pipe.
 *
 * On success, `*out_stderr` is null if stderr was not configured as a pipe or
 * was already taken.
 *
 * # Safety
 *
 * `child` must point to a live child returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] and be exclusively accessible
 * for the duration of this call. `out_stderr` must be properly aligned and
 * valid for writing a `*mut ModrinthSandboxPipeReader`, and must not contain an
 * owned handle.
 */
bool modrinth_sandbox_child_take_stderr(struct ModrinthSandboxChild *child,
                                        struct ModrinthSandboxPipeReader **out_stderr);

/**
 * Reads up to `buffer_len` bytes from a child output pipe.
 *
 * A successful read of zero bytes indicates end-of-file. A null `buffer` is
 * permitted only when `buffer_len` is zero.
 *
 * # Safety
 *
 * `reader` must point to a live reader returned by a child pipe accessor and
 * be exclusively accessible for the duration of this call. If `buffer_len` is
 * nonzero, `buffer` must be valid for writes of `buffer_len` bytes and may not
 * alias `reader` or `out_read`. `out_read` must be properly aligned and valid
 * for writing one `size_t`.
 */
bool modrinth_sandbox_pipe_reader_read(struct ModrinthSandboxPipeReader *reader,
                                       uint8_t *buffer,
                                       size_t buffer_len,
                                       size_t *out_read);

/**
 * Writes up to `buffer_len` bytes to a child input pipe.
 *
 * A null `buffer` is permitted only when `buffer_len` is zero.
 *
 * # Safety
 *
 * `writer` must point to a live writer returned by
 * [`modrinth_sandbox_child_take_stdin`] and be exclusively accessible for the
 * duration of this call. If `buffer_len` is nonzero, `buffer` must be valid for
 * reads of `buffer_len` bytes and may not alias `writer` or `out_written`.
 * `out_written` must be properly aligned and valid for writing one `size_t`.
 */
bool modrinth_sandbox_pipe_writer_write(struct ModrinthSandboxPipeWriter *writer,
                                        const uint8_t *buffer,
                                        size_t buffer_len,
                                        size_t *out_written);

/**
 * Flushes a child input pipe.
 *
 * # Safety
 *
 * `writer` must point to a live writer returned by
 * [`modrinth_sandbox_child_take_stdin`] and be exclusively accessible for the
 * duration of this call.
 */
bool modrinth_sandbox_pipe_writer_flush(struct ModrinthSandboxPipeWriter *writer);

/**
 * Frees a child output pipe reader.
 *
 * # Safety
 *
 * `reader` must be null or a pointer returned by a child pipe accessor that
 * has not already been freed.
 */
void modrinth_sandbox_pipe_reader_free(struct ModrinthSandboxPipeReader *reader);

/**
 * Frees a child input pipe writer, closing the child's standard input.
 *
 * # Safety
 *
 * `writer` must be null or a pointer returned by
 * [`modrinth_sandbox_child_take_stdin`] that has not already been freed.
 */
void modrinth_sandbox_pipe_writer_free(struct ModrinthSandboxPipeWriter *writer);

/**
 * Frees a child returned by [`crate::ffi::modrinth_sandbox_spawn`].
 *
 * # Safety
 *
 * `child` must be null or a pointer returned by
 * [`crate::ffi::env::modrinth_sandbox_spawn`] that has not already been freed.
 */
void modrinth_sandbox_child_free(struct ModrinthSandboxChild *child);

/**
 * Copies a borrowed C command view into a Rust-owned sandbox command.
 *
 * Stdio values use `0` for null, `1` for inherit, and `2` for pipe.
 *
 * # Safety
 *
 * Every pointer reachable through `command_view` must uphold its string or
 * slice type's safety contract for the duration of this call. If `out_command`
 * is non-null, it must be properly aligned and valid for writing a
 * `*mut ModrinthSandboxCommand`, and must not contain an owned handle.
 */
bool modrinth_sandbox_prepare_command(struct ModrinthSandboxCommandView command_view,
                                      struct ModrinthSandboxCommand **out_command);

/**
 * Frees a command returned by [`modrinth_sandbox_prepare_command`].
 *
 * # Safety
 *
 * `command` must be null or a pointer returned by
 * [`modrinth_sandbox_prepare_command`] that has not already been freed.
 */
void modrinth_sandbox_command_free(struct ModrinthSandboxCommand *command);

/**
 * Creates a sandbox environment and returns an opaque, Rust-owned handle.
 *
 * # Safety
 *
 * If `out_env` is non-null, it must be properly aligned and valid for writing
 * a `*mut ModrinthSandboxEnv`. It must not currently contain an owned handle.
 */
bool modrinth_sandbox_create_env(struct ModrinthSandboxEnv **out_env);

/**
 * Creates an environment that launches processes without sandboxing.
 *
 * This applies no filesystem or network isolation. Sandbox-specific options,
 * including `die_with_parent`, are not enforced. Use [`modrinth_sandbox_spawn`]
 * to launch processes and [`modrinth_sandbox_env_free`] to release the handle.
 *
 * # Safety
 *
 * If `out_env` is non-null, it must be properly aligned and valid for writing
 * a `*mut ModrinthSandboxEnv`. It must not currently contain an owned handle.
 */
bool modrinth_sandbox_create_noop_env(struct ModrinthSandboxEnv **out_env);

/**
 * Frees a sandbox or no-op environment.
 *
 * Children spawned through the environment remain usable after the environment
 * is freed because they retain the runtime needed for asynchronous operations.
 *
 * # Safety
 *
 * `env` must be null or a pointer returned by
 * [`modrinth_sandbox_create_env`] or [`modrinth_sandbox_create_noop_env`]
 * that has not already been freed.
 */
void modrinth_sandbox_env_free(struct ModrinthSandboxEnv *env);

/**
 * Spawns a sandboxed child and consumes `*command`.
 *
 * Once a non-null command handle has been validated, `*command` is set to
 * null and the command is consumed whether spawning succeeds or fails.
 *
 * # Safety
 *
 * `env` must point to a live environment returned by
 * [`modrinth_sandbox_create_env`] or [`modrinth_sandbox_create_noop_env`]
 * and must not be freed for the duration of
 * this call. `command` must point to valid, writable pointer storage, and a
 * non-null `*command` must be a uniquely owned handle returned by
 * [`crate::ffi::modrinth_sandbox_prepare_command`]. If `out_child` is
 * non-null, it must be properly aligned and valid for writing a
 * `*mut ModrinthSandboxChild`, and must not contain an owned handle.
 */
bool modrinth_sandbox_spawn(const struct ModrinthSandboxEnv *env,
                            struct ModrinthSandboxCommand **command,
                            struct ModrinthSandboxChild **out_child);

/**
 * Returns the most recent FFI error message.
 *
 * The returned message is not null-terminated and remains valid until the
 * next FFI operation that updates the last error.
 *
 * # Safety
 *
 * `out_message` and `out_message_len` must be valid, properly aligned,
 * writable pointers.
 */
void modrinth_sandbox_get_last_error(const uint8_t **out_message, size_t *out_message_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MODRINTH_SANDBOX_H */
