// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hooks } from "./lib-types.d";
import type { LinkedData } from "./lib-types.d";
import type { MemorySettings } from "./lib-types.d";
import type { ModLoader } from "./lib-types.d";
import type { WindowSize } from "./lib-types.d";

export type EditProfile = { name: string | null, game_version: string | null, loader: ModLoader | null, loader_version: string | null | null, groups: Array<string> | null, linked_data: LinkedData | null | null, java_path: string | null | null, extra_launch_args: Array<string> | null | null, custom_env_vars: Array<[string, string]> | null | null, memory: MemorySettings | null | null, force_fullscreen: boolean | null | null, game_resolution: WindowSize | null | null, hooks: Hooks | null, };
