// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheBehaviour = "stale_while_revalidate_skip_offline" | "stale_while_revalidate" | "must_revalidate" | "bypass";

export type FileMetadata = { project_id: string, version_id: string, };

/**
 * Game initialization hooks
 */
export type Hooks = { pre_launch: string | null, wrapper: string | null, post_exit: string | null, };

export type JavaVersion = { major_version: number, version: string, architecture: string, path: string, };

export type LinkedData = { project_id: string, version_id: string, locked: boolean, };

/**
 * Minecraft memory settings
 */
export type MemorySettings = { maximum: number, };

export type ModLoader = "vanilla" | "forge" | "fabric" | "quilt" | "neoforge";

export type ProcessMetadata = { uuid: string, profile_path: string, start_time: string, };

export type Profile = { path: string, install_stage: ProfileInstallStage, name: string, icon_path: string | null, game_version: string, loader: ModLoader, loader_version: string | null, groups: Array<string>, linked_data: LinkedData | null, created: string, modified: string, last_played: string | null, submitted_time_played: bigint, recent_time_played: bigint, java_path: string | null, extra_launch_args: Array<string> | null, custom_env_vars: Array<[string, string]> | null, memory: MemorySettings | null, force_fullscreen: boolean | null, game_resolution: WindowSize | null, hooks: Hooks, };

export type ProfileFile = { hash: string, file_name: string, size: bigint, metadata: FileMetadata | null, update_version_id: string | null, project_type: ProjectType, };

export type ProfileInstallStage = "installed" | "minecraft_installing" | "pack_installed" | "pack_installing" | "not_installed";

export type ProjectType = "mod" | "datapack" | "resourcepack" | "shaderpack";

/**
 * Game window size
 */
export type WindowSize = [number, number];
