export const defaultLicenseIds = [
	'',
	'All-Rights-Reserved',
	'Apache-2.0',
	'BSD-2-Clause',
	'BSD-3-Clause',
	'CC0-1.0',
	'CC-BY-4.0',
	'CC-BY-SA-4.0',
	'CC-BY-NC-4.0',
	'CC-BY-NC-SA-4.0',
	'CC-BY-ND-4.0',
	'CC-BY-NC-ND-4.0',
	'AGPL-3.0',
	'LGPL-2.1',
	'LGPL-3.0',
	'GPL-2.0',
	'GPL-3.0',
	'ISC',
	'MIT',
	'MPL-2.0',
	'Zlib',
] as const
