[package]
name = "theseus_playground"
edition.workspace = true

[dependencies]
enumset = { workspace = true }
theseus = { workspace = true, features = ["cli"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
