[package]
name = "theseus_playground"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
theseus = { path = "../../packages/app-lib", features = ["cli"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
url = "2.2"
webbrowser = "0.8.13"
dunce = "1.0.3"

futures = "0.3"
uuid = { version = "1.1", features = ["serde", "v4"] }

tracing = "0.1.37"
tracing-subscriber = "0.3.18"
tracing-error = "0.2.0"
