[package]
name = "pyro-console"
version = "0.1.0"
authors = ["not-nullptr <needhelpwithrift@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.76", features = [
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
    'EventTarget',
    'WheelEvent',
    'Performance',
    'TextMetrics',
    'DomRect',
    'OffscreenCanvas',
    'OffscreenCanvasRenderingContext2d',
    'DedicatedWorkerGlobalScope',
] }
console_log = "1.0.0"
log = "0.4.22"
rust-fuzzy-search = "0.1.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
