on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  shear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      - uses: cargo-bins/cargo-binstall@dc19f1e48450eefe5a29b8da6c6b00a87d730b37 # v1.18.1
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear
