on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  shear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear
