name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

      - uses: nrwl/nx-set-shas@v3

      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track master origin/master
        if: ${{ github.event_name == 'pull_request' }}

      - run: pnpm nx affected -t lint test build --parallel=3
