name: CLI Build + Lint

on:
  push:
    branches: [ master ]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./theseus_cli
    steps:
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - uses: actions-rs/cargo@v1
        name: Build program
        with:
          command: build
          args: --bin theseus_cli

      - name: Run Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --bin theseus_cli
