name: daedalus-docker-build

on:
  push:
    branches:
      - 'main'
      - 'prod'
    paths:
      - .github/workflows/daedalus-docker.yml
      - .github/workflows/rust-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
      - Cargo.toml
      - Cargo.lock
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/daedalus-docker.yml
      - .github/workflows/rust-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
      - Cargo.toml
      - Cargo.lock
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod' }}

jobs:
  daedalus:
    uses: ./.github/workflows/rust-docker.yml
    secrets:
      ARGOCD_DEPLOY_KEY: ${{ secrets.ARGOCD_DEPLOY_KEY }}
    with:
      package: daedalus_client
      project-dir: apps/daedalus_client
      runner: namespace-profile-medium-amd64
      image-name: daedalus
      application-set: launcher-meta
