name: daedalus-docker-build

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/daedalus-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/daedalus-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
  merge_group:
    types: [checks_requested]

jobs:
  docker:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: 📥 Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: ⚙️ Generate Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ghcr.io/modrinth/daedalus
          labels: |
            org.opencontainers.image.title=daedalus
            org.opencontainers.image.description=Modrinth game metadata query client
            org.opencontainers.image.licenses=MIT
          annotations: |
            org.opencontainers.image.title=daedalus
            org.opencontainers.image.description=Modrinth game metadata query client
            org.opencontainers.image.licenses=MIT

      - name: 🔑 Login to GitHub Packages
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          file: ./apps/daedalus_client/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          cache-from: type=registry,ref=ghcr.io/modrinth/daedalus:main
          cache-to: type=inline
