name: Labrinth Build

on:
  push:
    branches:
      - 'main'
      - 'prod'
    paths:
      - .github/workflows/labrinth-build.yml
      - .github/workflows/rust-docker.yml
      - 'apps/labrinth/**'
      - 'packages/**'
      - '!packages/api-client/**'
      - '!packages/app-lib/**'
      - Cargo.toml
      - Cargo.lock
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/labrinth-build.yml
      - .github/workflows/rust-docker.yml
      - 'apps/labrinth/**'
      - 'packages/**'
      - '!packages/api-client/**'
      - '!packages/app-lib/**'
      - Cargo.toml
      - Cargo.lock
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod' }}

jobs:
  labrinth:
    uses: ./.github/workflows/rust-docker.yml
    secrets:
      ARGOCD_DEPLOY_KEY: ${{ secrets.ARGOCD_DEPLOY_KEY }}
    with:
      package: labrinth
      profile: release-labrinth
      project-dir: apps/labrinth
      stage-paths: migrations assets
      runner: namespace-profile-modrinth-labrinth
      image-name: labrinth
      application-set: labrinth
